// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"radar/internal/domain/service"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GenerateTokens provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateTokens(userID uuid.UUID, roles []string) (string, string, error) {
	ret := _mock.Called(userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokens")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []string) (string, string, error)); ok {
		return returnFunc(userID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []string) string); ok {
		r0 = returnFunc(userID, roles)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, []string) string); ok {
		r1 = returnFunc(userID, roles)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID, []string) error); ok {
		r2 = returnFunc(userID, roles)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenService_GenerateTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokens'
type MockTokenService_GenerateTokens_Call struct {
	*mock.Call
}

// GenerateTokens is a helper method to define mock.On call
//   - userID uuid.UUID
//   - roles []string
func (_e *MockTokenService_Expecter) GenerateTokens(userID interface{}, roles interface{}) *MockTokenService_GenerateTokens_Call {
	return &MockTokenService_GenerateTokens_Call{Call: _e.mock.On("GenerateTokens", userID, roles)}
}

func (_c *MockTokenService_GenerateTokens_Call) Run(run func(userID uuid.UUID, roles []string)) *MockTokenService_GenerateTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_GenerateTokens_Call) Return(accessToken string, refreshToken string, err error) *MockTokenService_GenerateTokens_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockTokenService_GenerateTokens_Call) RunAndReturn(run func(userID uuid.UUID, roles []string) (string, string, error)) *MockTokenService_GenerateTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenDuration provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GetRefreshTokenDuration() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTokenService_GetRefreshTokenDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenDuration'
type MockTokenService_GetRefreshTokenDuration_Call struct {
	*mock.Call
}

// GetRefreshTokenDuration is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) GetRefreshTokenDuration() *MockTokenService_GetRefreshTokenDuration_Call {
	return &MockTokenService_GetRefreshTokenDuration_Call{Call: _e.mock.On("GetRefreshTokenDuration")}
}

func (_c *MockTokenService_GetRefreshTokenDuration_Call) Run(run func()) *MockTokenService_GetRefreshTokenDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_GetRefreshTokenDuration_Call) Return(duration time.Duration) *MockTokenService_GetRefreshTokenDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTokenService_GetRefreshTokenDuration_Call) RunAndReturn(run func() time.Duration) *MockTokenService_GetRefreshTokenDuration_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) HashToken(token string) string {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenService_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockTokenService_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) HashToken(token interface{}) *MockTokenService_HashToken_Call {
	return &MockTokenService_HashToken_Call{Call: _e.mock.On("HashToken", token)}
}

func (_c *MockTokenService_HashToken_Call) Run(run func(token string)) *MockTokenService_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_HashToken_Call) Return(s string) *MockTokenService_HashToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenService_HashToken_Call) RunAndReturn(run func(token string) string) *MockTokenService_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// RotateTokens provides a mock function for the type MockTokenService
func (_mock *MockTokenService) RotateTokens(userID uuid.UUID, roles []string) (string, string, string, error) {
	ret := _mock.Called(userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for RotateTokens")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []string) (string, string, string, error)); ok {
		return returnFunc(userID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []string) string); ok {
		r0 = returnFunc(userID, roles)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, []string) string); ok {
		r1 = returnFunc(userID, roles)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID, []string) string); ok {
		r2 = returnFunc(userID, roles)
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func(uuid.UUID, []string) error); ok {
		r3 = returnFunc(userID, roles)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockTokenService_RotateTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateTokens'
type MockTokenService_RotateTokens_Call struct {
	*mock.Call
}

// RotateTokens is a helper method to define mock.On call
//   - userID uuid.UUID
//   - roles []string
func (_e *MockTokenService_Expecter) RotateTokens(userID interface{}, roles interface{}) *MockTokenService_RotateTokens_Call {
	return &MockTokenService_RotateTokens_Call{Call: _e.mock.On("RotateTokens", userID, roles)}
}

func (_c *MockTokenService_RotateTokens_Call) Run(run func(userID uuid.UUID, roles []string)) *MockTokenService_RotateTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_RotateTokens_Call) Return(accessToken string, refreshToken string, refreshTokenHash string, err error) *MockTokenService_RotateTokens_Call {
	_c.Call.Return(accessToken, refreshToken, refreshTokenHash, err)
	return _c
}

func (_c *MockTokenService_RotateTokens_Call) RunAndReturn(run func(userID uuid.UUID, roles []string) (string, string, string, error)) *MockTokenService_RotateTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) ValidateToken(tokenString string) (*service.Claims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *service.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*service.Claims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *service.Claims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenService_Expecter) ValidateToken(tokenString interface{}) *MockTokenService_ValidateToken_Call {
	return &MockTokenService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *MockTokenService_ValidateToken_Call) Run(run func(tokenString string)) *MockTokenService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_ValidateToken_Call) Return(claims *service.Claims, err error) *MockTokenService_ValidateToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockTokenService_ValidateToken_Call) RunAndReturn(run func(tokenString string) (*service.Claims, error)) *MockTokenService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
