// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"radar/internal/domain/entity"
	"radar/internal/domain/service"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOAuthAuthService creates a new instance of MockOAuthAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthAuthService {
	mock := &MockOAuthAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOAuthAuthService is an autogenerated mock type for the OAuthAuthService type
type MockOAuthAuthService struct {
	mock.Mock
}

type MockOAuthAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthAuthService) EXPECT() *MockOAuthAuthService_Expecter {
	return &MockOAuthAuthService_Expecter{mock: &_m.Mock}
}

// GetProvider provides a mock function for the type MockOAuthAuthService
func (_mock *MockOAuthAuthService) GetProvider() entity.ProviderType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProvider")
	}

	var r0 entity.ProviderType
	if returnFunc, ok := ret.Get(0).(func() entity.ProviderType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entity.ProviderType)
	}
	return r0
}

// MockOAuthAuthService_GetProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProvider'
type MockOAuthAuthService_GetProvider_Call struct {
	*mock.Call
}

// GetProvider is a helper method to define mock.On call
func (_e *MockOAuthAuthService_Expecter) GetProvider() *MockOAuthAuthService_GetProvider_Call {
	return &MockOAuthAuthService_GetProvider_Call{Call: _e.mock.On("GetProvider")}
}

func (_c *MockOAuthAuthService_GetProvider_Call) Run(run func()) *MockOAuthAuthService_GetProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOAuthAuthService_GetProvider_Call) Return(providerType entity.ProviderType) *MockOAuthAuthService_GetProvider_Call {
	_c.Call.Return(providerType)
	return _c
}

func (_c *MockOAuthAuthService_GetProvider_Call) RunAndReturn(run func() entity.ProviderType) *MockOAuthAuthService_GetProvider_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyIDToken provides a mock function for the type MockOAuthAuthService
func (_mock *MockOAuthAuthService) VerifyIDToken(ctx context.Context, idToken string) (*service.OAuthUser, error) {
	ret := _mock.Called(ctx, idToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIDToken")
	}

	var r0 *service.OAuthUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.OAuthUser, error)); ok {
		return returnFunc(ctx, idToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.OAuthUser); ok {
		r0 = returnFunc(ctx, idToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.OAuthUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthAuthService_VerifyIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyIDToken'
type MockOAuthAuthService_VerifyIDToken_Call struct {
	*mock.Call
}

// VerifyIDToken is a helper method to define mock.On call
//   - ctx context.Context
//   - idToken string
func (_e *MockOAuthAuthService_Expecter) VerifyIDToken(ctx interface{}, idToken interface{}) *MockOAuthAuthService_VerifyIDToken_Call {
	return &MockOAuthAuthService_VerifyIDToken_Call{Call: _e.mock.On("VerifyIDToken", ctx, idToken)}
}

func (_c *MockOAuthAuthService_VerifyIDToken_Call) Run(run func(ctx context.Context, idToken string)) *MockOAuthAuthService_VerifyIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOAuthAuthService_VerifyIDToken_Call) Return(oAuthUser *service.OAuthUser, err error) *MockOAuthAuthService_VerifyIDToken_Call {
	_c.Call.Return(oAuthUser, err)
	return _c
}

func (_c *MockOAuthAuthService_VerifyIDToken_Call) RunAndReturn(run func(ctx context.Context, idToken string) (*service.OAuthUser, error)) *MockOAuthAuthService_VerifyIDToken_Call {
	_c.Call.Return(run)
	return _c
}
