packages:
  radar/internal/domain/repository:
    config:
      dir: "{{.ConfigDir}}/internal/mocks/repository"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
    interfaces:
      AddressRepository:
      AuthRepository:
      DeviceRepository:
      NotificationRepository:
      RefreshTokenRepository:
      SubscriptionRepository:
      TransactionManager:
      RepositoryFactory:
      UserRepository:
  radar/internal/domain/service:
    config:
      dir: "{{.ConfigDir}}/internal/mocks/service"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
    interfaces:
      NotificationService:
      OAuthAuthService:
      PasswordHasher:
      QRCodeService:
      TokenService:
