// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"radar/internal/domain/entity"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// CountActiveSessionsByUserID provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) CountActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveSessionsByUserID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_CountActiveSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveSessionsByUserID'
type MockRefreshTokenRepository_CountActiveSessionsByUserID_Call struct {
	*mock.Call
}

// CountActiveSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) CountActiveSessionsByUserID(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_CountActiveSessionsByUserID_Call {
	return &MockRefreshTokenRepository_CountActiveSessionsByUserID_Call{Call: _e.mock.On("CountActiveSessionsByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_CountActiveSessionsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRefreshTokenRepository_CountActiveSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_CountActiveSessionsByUserID_Call) Return(n int, err error) *MockRefreshTokenRepository_CountActiveSessionsByUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRefreshTokenRepository_CountActiveSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int, error)) *MockRefreshTokenRepository_CountActiveSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefreshToken provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) CreateRefreshToken(ctx context.Context, token *entity.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockRefreshTokenRepository_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *entity.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) CreateRefreshToken(ctx interface{}, token interface{}) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	return &MockRefreshTokenRepository_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, token)}
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) Run(run func(ctx context.Context, token *entity.RefreshToken)) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*entity.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) Return(err error) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token *entity.RefreshToken) error) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredRefreshTokens provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) DeleteExpiredRefreshTokens(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredRefreshTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredRefreshTokens'
type MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call struct {
	*mock.Call
}

// DeleteExpiredRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRefreshTokenRepository_Expecter) DeleteExpiredRefreshTokens(ctx interface{}) *MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call {
	return &MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call{Call: _e.mock.On("DeleteExpiredRefreshTokens", ctx)}
}

func (_c *MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call) Run(run func(ctx context.Context)) *MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call) Return(err error) *MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call) RunAndReturn(run func(ctx context.Context) error) *MockRefreshTokenRepository_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) DeleteRefreshToken(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockRefreshTokenRepository_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) DeleteRefreshToken(ctx interface{}, id interface{}) *MockRefreshTokenRepository_DeleteRefreshToken_Call {
	return &MockRefreshTokenRepository_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, id)}
}

func (_c *MockRefreshTokenRepository_DeleteRefreshToken_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRefreshTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteRefreshToken_Call) Return(err error) *MockRefreshTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRefreshTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshTokenByHash provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshTokenByHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshTokenByHash'
type MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call struct {
	*mock.Call
}

// DeleteRefreshTokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshTokenRepository_Expecter) DeleteRefreshTokenByHash(ctx interface{}, tokenHash interface{}) *MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call {
	return &MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call{Call: _e.mock.On("DeleteRefreshTokenByHash", ctx, tokenHash)}
}

func (_c *MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call) Return(err error) *MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *MockRefreshTokenRepository_DeleteRefreshTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshTokensByUserID provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) DeleteRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshTokensByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshTokensByUserID'
type MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call struct {
	*mock.Call
}

// DeleteRefreshTokensByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) DeleteRefreshTokensByUserID(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call {
	return &MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call{Call: _e.mock.On("DeleteRefreshTokensByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call) Return(err error) *MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockRefreshTokenRepository_DeleteRefreshTokensByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshTokenByHash provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) FindRefreshTokenByHash(ctx context.Context, tokenHash string) (*entity.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshTokenByHash")
	}

	var r0 *entity.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_FindRefreshTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshTokenByHash'
type MockRefreshTokenRepository_FindRefreshTokenByHash_Call struct {
	*mock.Call
}

// FindRefreshTokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshTokenRepository_Expecter) FindRefreshTokenByHash(ctx interface{}, tokenHash interface{}) *MockRefreshTokenRepository_FindRefreshTokenByHash_Call {
	return &MockRefreshTokenRepository_FindRefreshTokenByHash_Call{Call: _e.mock.On("FindRefreshTokenByHash", ctx, tokenHash)}
}

func (_c *MockRefreshTokenRepository_FindRefreshTokenByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshTokenRepository_FindRefreshTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindRefreshTokenByHash_Call) Return(refreshToken *entity.RefreshToken, err error) *MockRefreshTokenRepository_FindRefreshTokenByHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepository_FindRefreshTokenByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*entity.RefreshToken, error)) *MockRefreshTokenRepository_FindRefreshTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshTokenByID provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) FindRefreshTokenByID(ctx context.Context, id uuid.UUID) (*entity.RefreshToken, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshTokenByID")
	}

	var r0 *entity.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.RefreshToken, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.RefreshToken); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_FindRefreshTokenByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshTokenByID'
type MockRefreshTokenRepository_FindRefreshTokenByID_Call struct {
	*mock.Call
}

// FindRefreshTokenByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) FindRefreshTokenByID(ctx interface{}, id interface{}) *MockRefreshTokenRepository_FindRefreshTokenByID_Call {
	return &MockRefreshTokenRepository_FindRefreshTokenByID_Call{Call: _e.mock.On("FindRefreshTokenByID", ctx, id)}
}

func (_c *MockRefreshTokenRepository_FindRefreshTokenByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRefreshTokenRepository_FindRefreshTokenByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindRefreshTokenByID_Call) Return(refreshToken *entity.RefreshToken, err error) *MockRefreshTokenRepository_FindRefreshTokenByID_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepository_FindRefreshTokenByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.RefreshToken, error)) *MockRefreshTokenRepository_FindRefreshTokenByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshTokensByUserID provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) FindRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) ([]*entity.RefreshToken, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshTokensByUserID")
	}

	var r0 []*entity.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.RefreshToken, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.RefreshToken); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_FindRefreshTokensByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshTokensByUserID'
type MockRefreshTokenRepository_FindRefreshTokensByUserID_Call struct {
	*mock.Call
}

// FindRefreshTokensByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) FindRefreshTokensByUserID(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_FindRefreshTokensByUserID_Call {
	return &MockRefreshTokenRepository_FindRefreshTokensByUserID_Call{Call: _e.mock.On("FindRefreshTokensByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_FindRefreshTokensByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRefreshTokenRepository_FindRefreshTokensByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindRefreshTokensByUserID_Call) Return(refreshTokens []*entity.RefreshToken, err error) *MockRefreshTokenRepository_FindRefreshTokensByUserID_Call {
	_c.Call.Return(refreshTokens, err)
	return _c
}

func (_c *MockRefreshTokenRepository_FindRefreshTokensByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*entity.RefreshToken, error)) *MockRefreshTokenRepository_FindRefreshTokensByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRefreshToken provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) UpdateRefreshToken(ctx context.Context, token *entity.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_UpdateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRefreshToken'
type MockRefreshTokenRepository_UpdateRefreshToken_Call struct {
	*mock.Call
}

// UpdateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *entity.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) UpdateRefreshToken(ctx interface{}, token interface{}) *MockRefreshTokenRepository_UpdateRefreshToken_Call {
	return &MockRefreshTokenRepository_UpdateRefreshToken_Call{Call: _e.mock.On("UpdateRefreshToken", ctx, token)}
}

func (_c *MockRefreshTokenRepository_UpdateRefreshToken_Call) Run(run func(ctx context.Context, token *entity.RefreshToken)) *MockRefreshTokenRepository_UpdateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*entity.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_UpdateRefreshToken_Call) Return(err error) *MockRefreshTokenRepository_UpdateRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_UpdateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token *entity.RefreshToken) error) *MockRefreshTokenRepository_UpdateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
