// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"radar/internal/domain/entity"
	"radar/internal/domain/policy"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoginAttemptRepository creates a new instance of MockLoginAttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginAttemptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginAttemptRepository {
	mock := &MockLoginAttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginAttemptRepository is an autogenerated mock type for the LoginAttemptRepository type
type MockLoginAttemptRepository struct {
	mock.Mock
}

type MockLoginAttemptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginAttemptRepository) EXPECT() *MockLoginAttemptRepository_Expecter {
	return &MockLoginAttemptRepository_Expecter{mock: &_m.Mock}
}

// DecayLockoutCounts provides a mock function for the type MockLoginAttemptRepository
func (_mock *MockLoginAttemptRepository) DecayLockoutCounts(ctx context.Context, decayDays int) error {
	ret := _mock.Called(ctx, decayDays)

	if len(ret) == 0 {
		panic("no return value specified for DecayLockoutCounts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, decayDays)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginAttemptRepository_DecayLockoutCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecayLockoutCounts'
type MockLoginAttemptRepository_DecayLockoutCounts_Call struct {
	*mock.Call
}

// DecayLockoutCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - decayDays int
func (_e *MockLoginAttemptRepository_Expecter) DecayLockoutCounts(ctx interface{}, decayDays interface{}) *MockLoginAttemptRepository_DecayLockoutCounts_Call {
	return &MockLoginAttemptRepository_DecayLockoutCounts_Call{Call: _e.mock.On("DecayLockoutCounts", ctx, decayDays)}
}

func (_c *MockLoginAttemptRepository_DecayLockoutCounts_Call) Run(run func(ctx context.Context, decayDays int)) *MockLoginAttemptRepository_DecayLockoutCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoginAttemptRepository_DecayLockoutCounts_Call) Return(err error) *MockLoginAttemptRepository_DecayLockoutCounts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginAttemptRepository_DecayLockoutCounts_Call) RunAndReturn(run func(ctx context.Context, decayDays int) error) *MockLoginAttemptRepository_DecayLockoutCounts_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateByAttemptKey provides a mock function for the type MockLoginAttemptRepository
func (_mock *MockLoginAttemptRepository) FindOrCreateByAttemptKey(ctx context.Context, attemptKey string, userID *uuid.UUID) (*entity.LoginAttempt, error) {
	ret := _mock.Called(ctx, attemptKey, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateByAttemptKey")
	}

	var r0 *entity.LoginAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID) (*entity.LoginAttempt, error)); ok {
		return returnFunc(ctx, attemptKey, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID) *entity.LoginAttempt); ok {
		r0 = returnFunc(ctx, attemptKey, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LoginAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, attemptKey, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateByAttemptKey'
type MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call struct {
	*mock.Call
}

// FindOrCreateByAttemptKey is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptKey string
//   - userID *uuid.UUID
func (_e *MockLoginAttemptRepository_Expecter) FindOrCreateByAttemptKey(ctx interface{}, attemptKey interface{}, userID interface{}) *MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call {
	return &MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call{Call: _e.mock.On("FindOrCreateByAttemptKey", ctx, attemptKey, userID)}
}

func (_c *MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call) Run(run func(ctx context.Context, attemptKey string, userID *uuid.UUID)) *MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call) Return(loginAttempt *entity.LoginAttempt, err error) *MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call {
	_c.Call.Return(loginAttempt, err)
	return _c
}

func (_c *MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call) RunAndReturn(run func(ctx context.Context, attemptKey string, userID *uuid.UUID) (*entity.LoginAttempt, error)) *MockLoginAttemptRepository_FindOrCreateByAttemptKey_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementFailedCount provides a mock function for the type MockLoginAttemptRepository
func (_mock *MockLoginAttemptRepository) IncrementFailedCount(ctx context.Context, attemptKey string, maxAttempts int, lockoutPolicy policy.LoginThrottlePolicy) (*entity.LoginAttempt, error) {
	ret := _mock.Called(ctx, attemptKey, maxAttempts, lockoutPolicy)

	if len(ret) == 0 {
		panic("no return value specified for IncrementFailedCount")
	}

	var r0 *entity.LoginAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, policy.LoginThrottlePolicy) (*entity.LoginAttempt, error)); ok {
		return returnFunc(ctx, attemptKey, maxAttempts, lockoutPolicy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, policy.LoginThrottlePolicy) *entity.LoginAttempt); ok {
		r0 = returnFunc(ctx, attemptKey, maxAttempts, lockoutPolicy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LoginAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, policy.LoginThrottlePolicy) error); ok {
		r1 = returnFunc(ctx, attemptKey, maxAttempts, lockoutPolicy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginAttemptRepository_IncrementFailedCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementFailedCount'
type MockLoginAttemptRepository_IncrementFailedCount_Call struct {
	*mock.Call
}

// IncrementFailedCount is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptKey string
//   - maxAttempts int
//   - lockoutPolicy policy.LoginThrottlePolicy
func (_e *MockLoginAttemptRepository_Expecter) IncrementFailedCount(ctx interface{}, attemptKey interface{}, maxAttempts interface{}, lockoutPolicy interface{}) *MockLoginAttemptRepository_IncrementFailedCount_Call {
	return &MockLoginAttemptRepository_IncrementFailedCount_Call{Call: _e.mock.On("IncrementFailedCount", ctx, attemptKey, maxAttempts, lockoutPolicy)}
}

func (_c *MockLoginAttemptRepository_IncrementFailedCount_Call) Run(run func(ctx context.Context, attemptKey string, maxAttempts int, lockoutPolicy policy.LoginThrottlePolicy)) *MockLoginAttemptRepository_IncrementFailedCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 policy.LoginThrottlePolicy
		if args[3] != nil {
			arg3 = args[3].(policy.LoginThrottlePolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLoginAttemptRepository_IncrementFailedCount_Call) Return(loginAttempt *entity.LoginAttempt, err error) *MockLoginAttemptRepository_IncrementFailedCount_Call {
	_c.Call.Return(loginAttempt, err)
	return _c
}

func (_c *MockLoginAttemptRepository_IncrementFailedCount_Call) RunAndReturn(run func(ctx context.Context, attemptKey string, maxAttempts int, lockoutPolicy policy.LoginThrottlePolicy) (*entity.LoginAttempt, error)) *MockLoginAttemptRepository_IncrementFailedCount_Call {
	_c.Call.Return(run)
	return _c
}

// ResetForAccountCreation provides a mock function for the type MockLoginAttemptRepository
func (_mock *MockLoginAttemptRepository) ResetForAccountCreation(ctx context.Context, attemptKey string, userID uuid.UUID) error {
	ret := _mock.Called(ctx, attemptKey, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResetForAccountCreation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, attemptKey, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginAttemptRepository_ResetForAccountCreation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetForAccountCreation'
type MockLoginAttemptRepository_ResetForAccountCreation_Call struct {
	*mock.Call
}

// ResetForAccountCreation is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptKey string
//   - userID uuid.UUID
func (_e *MockLoginAttemptRepository_Expecter) ResetForAccountCreation(ctx interface{}, attemptKey interface{}, userID interface{}) *MockLoginAttemptRepository_ResetForAccountCreation_Call {
	return &MockLoginAttemptRepository_ResetForAccountCreation_Call{Call: _e.mock.On("ResetForAccountCreation", ctx, attemptKey, userID)}
}

func (_c *MockLoginAttemptRepository_ResetForAccountCreation_Call) Run(run func(ctx context.Context, attemptKey string, userID uuid.UUID)) *MockLoginAttemptRepository_ResetForAccountCreation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoginAttemptRepository_ResetForAccountCreation_Call) Return(err error) *MockLoginAttemptRepository_ResetForAccountCreation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginAttemptRepository_ResetForAccountCreation_Call) RunAndReturn(run func(ctx context.Context, attemptKey string, userID uuid.UUID) error) *MockLoginAttemptRepository_ResetForAccountCreation_Call {
	_c.Call.Return(run)
	return _c
}

// ResetOnSuccess provides a mock function for the type MockLoginAttemptRepository
func (_mock *MockLoginAttemptRepository) ResetOnSuccess(ctx context.Context, attemptKey string) error {
	ret := _mock.Called(ctx, attemptKey)

	if len(ret) == 0 {
		panic("no return value specified for ResetOnSuccess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, attemptKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginAttemptRepository_ResetOnSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetOnSuccess'
type MockLoginAttemptRepository_ResetOnSuccess_Call struct {
	*mock.Call
}

// ResetOnSuccess is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptKey string
func (_e *MockLoginAttemptRepository_Expecter) ResetOnSuccess(ctx interface{}, attemptKey interface{}) *MockLoginAttemptRepository_ResetOnSuccess_Call {
	return &MockLoginAttemptRepository_ResetOnSuccess_Call{Call: _e.mock.On("ResetOnSuccess", ctx, attemptKey)}
}

func (_c *MockLoginAttemptRepository_ResetOnSuccess_Call) Run(run func(ctx context.Context, attemptKey string)) *MockLoginAttemptRepository_ResetOnSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoginAttemptRepository_ResetOnSuccess_Call) Return(err error) *MockLoginAttemptRepository_ResetOnSuccess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginAttemptRepository_ResetOnSuccess_Call) RunAndReturn(run func(ctx context.Context, attemptKey string) error) *MockLoginAttemptRepository_ResetOnSuccess_Call {
	_c.Call.Return(run)
	return _c
}
