// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"radar/internal/domain/entity"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// CreateAuthentication provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateAuthentication(ctx context.Context, auth *entity.Authentication) error {
	ret := _mock.Called(ctx, auth)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthentication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Authentication) error); ok {
		r0 = returnFunc(ctx, auth)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_CreateAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthentication'
type MockAuthRepository_CreateAuthentication_Call struct {
	*mock.Call
}

// CreateAuthentication is a helper method to define mock.On call
//   - ctx context.Context
//   - auth *entity.Authentication
func (_e *MockAuthRepository_Expecter) CreateAuthentication(ctx interface{}, auth interface{}) *MockAuthRepository_CreateAuthentication_Call {
	return &MockAuthRepository_CreateAuthentication_Call{Call: _e.mock.On("CreateAuthentication", ctx, auth)}
}

func (_c *MockAuthRepository_CreateAuthentication_Call) Run(run func(ctx context.Context, auth *entity.Authentication)) *MockAuthRepository_CreateAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Authentication
		if args[1] != nil {
			arg1 = args[1].(*entity.Authentication)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_CreateAuthentication_Call) Return(err error) *MockAuthRepository_CreateAuthentication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_CreateAuthentication_Call) RunAndReturn(run func(ctx context.Context, auth *entity.Authentication) error) *MockAuthRepository_CreateAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAuthentication provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) DeleteAuthentication(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAuthentication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_DeleteAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAuthentication'
type MockAuthRepository_DeleteAuthentication_Call struct {
	*mock.Call
}

// DeleteAuthentication is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthRepository_Expecter) DeleteAuthentication(ctx interface{}, id interface{}) *MockAuthRepository_DeleteAuthentication_Call {
	return &MockAuthRepository_DeleteAuthentication_Call{Call: _e.mock.On("DeleteAuthentication", ctx, id)}
}

func (_c *MockAuthRepository_DeleteAuthentication_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthRepository_DeleteAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_DeleteAuthentication_Call) Return(err error) *MockAuthRepository_DeleteAuthentication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_DeleteAuthentication_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuthRepository_DeleteAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// FindAuthentication provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) FindAuthentication(ctx context.Context, provider entity.ProviderType, providerUserID string) (*entity.Authentication, error) {
	ret := _mock.Called(ctx, provider, providerUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindAuthentication")
	}

	var r0 *entity.Authentication
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ProviderType, string) (*entity.Authentication, error)); ok {
		return returnFunc(ctx, provider, providerUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ProviderType, string) *entity.Authentication); ok {
		r0 = returnFunc(ctx, provider, providerUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Authentication)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ProviderType, string) error); ok {
		r1 = returnFunc(ctx, provider, providerUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_FindAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAuthentication'
type MockAuthRepository_FindAuthentication_Call struct {
	*mock.Call
}

// FindAuthentication is a helper method to define mock.On call
//   - ctx context.Context
//   - provider entity.ProviderType
//   - providerUserID string
func (_e *MockAuthRepository_Expecter) FindAuthentication(ctx interface{}, provider interface{}, providerUserID interface{}) *MockAuthRepository_FindAuthentication_Call {
	return &MockAuthRepository_FindAuthentication_Call{Call: _e.mock.On("FindAuthentication", ctx, provider, providerUserID)}
}

func (_c *MockAuthRepository_FindAuthentication_Call) Run(run func(ctx context.Context, provider entity.ProviderType, providerUserID string)) *MockAuthRepository_FindAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ProviderType
		if args[1] != nil {
			arg1 = args[1].(entity.ProviderType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepository_FindAuthentication_Call) Return(authentication *entity.Authentication, err error) *MockAuthRepository_FindAuthentication_Call {
	_c.Call.Return(authentication, err)
	return _c
}

func (_c *MockAuthRepository_FindAuthentication_Call) RunAndReturn(run func(ctx context.Context, provider entity.ProviderType, providerUserID string) (*entity.Authentication, error)) *MockAuthRepository_FindAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// FindAuthenticationByUserIDAndProvider provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) FindAuthenticationByUserIDAndProvider(ctx context.Context, userID uuid.UUID, provider entity.ProviderType) (*entity.Authentication, error) {
	ret := _mock.Called(ctx, userID, provider)

	if len(ret) == 0 {
		panic("no return value specified for FindAuthenticationByUserIDAndProvider")
	}

	var r0 *entity.Authentication
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.ProviderType) (*entity.Authentication, error)); ok {
		return returnFunc(ctx, userID, provider)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.ProviderType) *entity.Authentication); ok {
		r0 = returnFunc(ctx, userID, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Authentication)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.ProviderType) error); ok {
		r1 = returnFunc(ctx, userID, provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAuthenticationByUserIDAndProvider'
type MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call struct {
	*mock.Call
}

// FindAuthenticationByUserIDAndProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - provider entity.ProviderType
func (_e *MockAuthRepository_Expecter) FindAuthenticationByUserIDAndProvider(ctx interface{}, userID interface{}, provider interface{}) *MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call {
	return &MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call{Call: _e.mock.On("FindAuthenticationByUserIDAndProvider", ctx, userID, provider)}
}

func (_c *MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call) Run(run func(ctx context.Context, userID uuid.UUID, provider entity.ProviderType)) *MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 entity.ProviderType
		if args[2] != nil {
			arg2 = args[2].(entity.ProviderType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call) Return(authentication *entity.Authentication, err error) *MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call {
	_c.Call.Return(authentication, err)
	return _c
}

func (_c *MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, provider entity.ProviderType) (*entity.Authentication, error)) *MockAuthRepository_FindAuthenticationByUserIDAndProvider_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuthenticationsByUserID provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) ListAuthenticationsByUserID(ctx context.Context, userID uuid.UUID) ([]*entity.Authentication, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAuthenticationsByUserID")
	}

	var r0 []*entity.Authentication
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Authentication, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Authentication); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Authentication)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_ListAuthenticationsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuthenticationsByUserID'
type MockAuthRepository_ListAuthenticationsByUserID_Call struct {
	*mock.Call
}

// ListAuthenticationsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthRepository_Expecter) ListAuthenticationsByUserID(ctx interface{}, userID interface{}) *MockAuthRepository_ListAuthenticationsByUserID_Call {
	return &MockAuthRepository_ListAuthenticationsByUserID_Call{Call: _e.mock.On("ListAuthenticationsByUserID", ctx, userID)}
}

func (_c *MockAuthRepository_ListAuthenticationsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthRepository_ListAuthenticationsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_ListAuthenticationsByUserID_Call) Return(authentications []*entity.Authentication, err error) *MockAuthRepository_ListAuthenticationsByUserID_Call {
	_c.Call.Return(authentications, err)
	return _c
}

func (_c *MockAuthRepository_ListAuthenticationsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*entity.Authentication, error)) *MockAuthRepository_ListAuthenticationsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAuthentication provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) UpdateAuthentication(ctx context.Context, auth *entity.Authentication) error {
	ret := _mock.Called(ctx, auth)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuthentication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Authentication) error); ok {
		r0 = returnFunc(ctx, auth)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_UpdateAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAuthentication'
type MockAuthRepository_UpdateAuthentication_Call struct {
	*mock.Call
}

// UpdateAuthentication is a helper method to define mock.On call
//   - ctx context.Context
//   - auth *entity.Authentication
func (_e *MockAuthRepository_Expecter) UpdateAuthentication(ctx interface{}, auth interface{}) *MockAuthRepository_UpdateAuthentication_Call {
	return &MockAuthRepository_UpdateAuthentication_Call{Call: _e.mock.On("UpdateAuthentication", ctx, auth)}
}

func (_c *MockAuthRepository_UpdateAuthentication_Call) Run(run func(ctx context.Context, auth *entity.Authentication)) *MockAuthRepository_UpdateAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Authentication
		if args[1] != nil {
			arg1 = args[1].(*entity.Authentication)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_UpdateAuthentication_Call) Return(err error) *MockAuthRepository_UpdateAuthentication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_UpdateAuthentication_Call) RunAndReturn(run func(ctx context.Context, auth *entity.Authentication) error) *MockAuthRepository_UpdateAuthentication_Call {
	_c.Call.Return(run)
	return _c
}
