// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"radar/internal/domain/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryFactory creates a new instance of MockRepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryFactory {
	mock := &MockRepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type MockRepositoryFactory struct {
	mock.Mock
}

type MockRepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryFactory) EXPECT() *MockRepositoryFactory_Expecter {
	return &MockRepositoryFactory_Expecter{mock: &_m.Mock}
}

// AddressRepo provides a mock function for the type MockRepositoryFactory
func (_mock *MockRepositoryFactory) AddressRepo() repository.AddressRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddressRepo")
	}

	var r0 repository.AddressRepository
	if returnFunc, ok := ret.Get(0).(func() repository.AddressRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.AddressRepository)
		}
	}
	return r0
}

// MockRepositoryFactory_AddressRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddressRepo'
type MockRepositoryFactory_AddressRepo_Call struct {
	*mock.Call
}

// AddressRepo is a helper method to define mock.On call
func (_e *MockRepositoryFactory_Expecter) AddressRepo() *MockRepositoryFactory_AddressRepo_Call {
	return &MockRepositoryFactory_AddressRepo_Call{Call: _e.mock.On("AddressRepo")}
}

func (_c *MockRepositoryFactory_AddressRepo_Call) Run(run func()) *MockRepositoryFactory_AddressRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryFactory_AddressRepo_Call) Return(addressRepository repository.AddressRepository) *MockRepositoryFactory_AddressRepo_Call {
	_c.Call.Return(addressRepository)
	return _c
}

func (_c *MockRepositoryFactory_AddressRepo_Call) RunAndReturn(run func() repository.AddressRepository) *MockRepositoryFactory_AddressRepo_Call {
	_c.Call.Return(run)
	return _c
}

// AuthRepo provides a mock function for the type MockRepositoryFactory
func (_mock *MockRepositoryFactory) AuthRepo() repository.AuthRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthRepo")
	}

	var r0 repository.AuthRepository
	if returnFunc, ok := ret.Get(0).(func() repository.AuthRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.AuthRepository)
		}
	}
	return r0
}

// MockRepositoryFactory_AuthRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthRepo'
type MockRepositoryFactory_AuthRepo_Call struct {
	*mock.Call
}

// AuthRepo is a helper method to define mock.On call
func (_e *MockRepositoryFactory_Expecter) AuthRepo() *MockRepositoryFactory_AuthRepo_Call {
	return &MockRepositoryFactory_AuthRepo_Call{Call: _e.mock.On("AuthRepo")}
}

func (_c *MockRepositoryFactory_AuthRepo_Call) Run(run func()) *MockRepositoryFactory_AuthRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryFactory_AuthRepo_Call) Return(authRepository repository.AuthRepository) *MockRepositoryFactory_AuthRepo_Call {
	_c.Call.Return(authRepository)
	return _c
}

func (_c *MockRepositoryFactory_AuthRepo_Call) RunAndReturn(run func() repository.AuthRepository) *MockRepositoryFactory_AuthRepo_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokenRepo provides a mock function for the type MockRepositoryFactory
func (_mock *MockRepositoryFactory) RefreshTokenRepo() repository.RefreshTokenRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokenRepo")
	}

	var r0 repository.RefreshTokenRepository
	if returnFunc, ok := ret.Get(0).(func() repository.RefreshTokenRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.RefreshTokenRepository)
		}
	}
	return r0
}

// MockRepositoryFactory_RefreshTokenRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokenRepo'
type MockRepositoryFactory_RefreshTokenRepo_Call struct {
	*mock.Call
}

// RefreshTokenRepo is a helper method to define mock.On call
func (_e *MockRepositoryFactory_Expecter) RefreshTokenRepo() *MockRepositoryFactory_RefreshTokenRepo_Call {
	return &MockRepositoryFactory_RefreshTokenRepo_Call{Call: _e.mock.On("RefreshTokenRepo")}
}

func (_c *MockRepositoryFactory_RefreshTokenRepo_Call) Run(run func()) *MockRepositoryFactory_RefreshTokenRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryFactory_RefreshTokenRepo_Call) Return(refreshTokenRepository repository.RefreshTokenRepository) *MockRepositoryFactory_RefreshTokenRepo_Call {
	_c.Call.Return(refreshTokenRepository)
	return _c
}

func (_c *MockRepositoryFactory_RefreshTokenRepo_Call) RunAndReturn(run func() repository.RefreshTokenRepository) *MockRepositoryFactory_RefreshTokenRepo_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepo provides a mock function for the type MockRepositoryFactory
func (_mock *MockRepositoryFactory) UserRepo() repository.UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepo")
	}

	var r0 repository.UserRepository
	if returnFunc, ok := ret.Get(0).(func() repository.UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserRepository)
		}
	}
	return r0
}

// MockRepositoryFactory_UserRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepo'
type MockRepositoryFactory_UserRepo_Call struct {
	*mock.Call
}

// UserRepo is a helper method to define mock.On call
func (_e *MockRepositoryFactory_Expecter) UserRepo() *MockRepositoryFactory_UserRepo_Call {
	return &MockRepositoryFactory_UserRepo_Call{Call: _e.mock.On("UserRepo")}
}

func (_c *MockRepositoryFactory_UserRepo_Call) Run(run func()) *MockRepositoryFactory_UserRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryFactory_UserRepo_Call) Return(userRepository repository.UserRepository) *MockRepositoryFactory_UserRepo_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockRepositoryFactory_UserRepo_Call) RunAndReturn(run func() repository.UserRepository) *MockRepositoryFactory_UserRepo_Call {
	_c.Call.Return(run)
	return _c
}
