// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"radar/internal/domain/entity"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// BatchCreateNotificationLogs provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) BatchCreateNotificationLogs(ctx context.Context, logs []*entity.NotificationLog) error {
	ret := _mock.Called(ctx, logs)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreateNotificationLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entity.NotificationLog) error); ok {
		r0 = returnFunc(ctx, logs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_BatchCreateNotificationLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreateNotificationLogs'
type MockNotificationRepository_BatchCreateNotificationLogs_Call struct {
	*mock.Call
}

// BatchCreateNotificationLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - logs []*entity.NotificationLog
func (_e *MockNotificationRepository_Expecter) BatchCreateNotificationLogs(ctx interface{}, logs interface{}) *MockNotificationRepository_BatchCreateNotificationLogs_Call {
	return &MockNotificationRepository_BatchCreateNotificationLogs_Call{Call: _e.mock.On("BatchCreateNotificationLogs", ctx, logs)}
}

func (_c *MockNotificationRepository_BatchCreateNotificationLogs_Call) Run(run func(ctx context.Context, logs []*entity.NotificationLog)) *MockNotificationRepository_BatchCreateNotificationLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entity.NotificationLog
		if args[1] != nil {
			arg1 = args[1].([]*entity.NotificationLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_BatchCreateNotificationLogs_Call) Return(err error) *MockNotificationRepository_BatchCreateNotificationLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_BatchCreateNotificationLogs_Call) RunAndReturn(run func(ctx context.Context, logs []*entity.NotificationLog) error) *MockNotificationRepository_BatchCreateNotificationLogs_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNotification provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) CreateNotification(ctx context.Context, notification *entity.MerchantLocationNotification) error {
	ret := _mock.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.MerchantLocationNotification) error); ok {
		r0 = returnFunc(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_CreateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotification'
type MockNotificationRepository_CreateNotification_Call struct {
	*mock.Call
}

// CreateNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *entity.MerchantLocationNotification
func (_e *MockNotificationRepository_Expecter) CreateNotification(ctx interface{}, notification interface{}) *MockNotificationRepository_CreateNotification_Call {
	return &MockNotificationRepository_CreateNotification_Call{Call: _e.mock.On("CreateNotification", ctx, notification)}
}

func (_c *MockNotificationRepository_CreateNotification_Call) Run(run func(ctx context.Context, notification *entity.MerchantLocationNotification)) *MockNotificationRepository_CreateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.MerchantLocationNotification
		if args[1] != nil {
			arg1 = args[1].(*entity.MerchantLocationNotification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_CreateNotification_Call) Return(err error) *MockNotificationRepository_CreateNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_CreateNotification_Call) RunAndReturn(run func(ctx context.Context, notification *entity.MerchantLocationNotification) error) *MockNotificationRepository_CreateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNotificationLog provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) CreateNotificationLog(ctx context.Context, log *entity.NotificationLog) error {
	ret := _mock.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotificationLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.NotificationLog) error); ok {
		r0 = returnFunc(ctx, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_CreateNotificationLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotificationLog'
type MockNotificationRepository_CreateNotificationLog_Call struct {
	*mock.Call
}

// CreateNotificationLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *entity.NotificationLog
func (_e *MockNotificationRepository_Expecter) CreateNotificationLog(ctx interface{}, log interface{}) *MockNotificationRepository_CreateNotificationLog_Call {
	return &MockNotificationRepository_CreateNotificationLog_Call{Call: _e.mock.On("CreateNotificationLog", ctx, log)}
}

func (_c *MockNotificationRepository_CreateNotificationLog_Call) Run(run func(ctx context.Context, log *entity.NotificationLog)) *MockNotificationRepository_CreateNotificationLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.NotificationLog
		if args[1] != nil {
			arg1 = args[1].(*entity.NotificationLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_CreateNotificationLog_Call) Return(err error) *MockNotificationRepository_CreateNotificationLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_CreateNotificationLog_Call) RunAndReturn(run func(ctx context.Context, log *entity.NotificationLog) error) *MockNotificationRepository_CreateNotificationLog_Call {
	_c.Call.Return(run)
	return _c
}

// FindNotificationByID provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) FindNotificationByID(ctx context.Context, id uuid.UUID) (*entity.MerchantLocationNotification, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindNotificationByID")
	}

	var r0 *entity.MerchantLocationNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.MerchantLocationNotification, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.MerchantLocationNotification); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.MerchantLocationNotification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_FindNotificationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNotificationByID'
type MockNotificationRepository_FindNotificationByID_Call struct {
	*mock.Call
}

// FindNotificationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotificationRepository_Expecter) FindNotificationByID(ctx interface{}, id interface{}) *MockNotificationRepository_FindNotificationByID_Call {
	return &MockNotificationRepository_FindNotificationByID_Call{Call: _e.mock.On("FindNotificationByID", ctx, id)}
}

func (_c *MockNotificationRepository_FindNotificationByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotificationRepository_FindNotificationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_FindNotificationByID_Call) Return(merchantLocationNotification *entity.MerchantLocationNotification, err error) *MockNotificationRepository_FindNotificationByID_Call {
	_c.Call.Return(merchantLocationNotification, err)
	return _c
}

func (_c *MockNotificationRepository_FindNotificationByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.MerchantLocationNotification, error)) *MockNotificationRepository_FindNotificationByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindNotificationsByMerchant provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) FindNotificationsByMerchant(ctx context.Context, merchantID uuid.UUID, limit int, offset int) ([]*entity.MerchantLocationNotification, error) {
	ret := _mock.Called(ctx, merchantID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindNotificationsByMerchant")
	}

	var r0 []*entity.MerchantLocationNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.MerchantLocationNotification, error)); ok {
		return returnFunc(ctx, merchantID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.MerchantLocationNotification); ok {
		r0 = returnFunc(ctx, merchantID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.MerchantLocationNotification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, merchantID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_FindNotificationsByMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNotificationsByMerchant'
type MockNotificationRepository_FindNotificationsByMerchant_Call struct {
	*mock.Call
}

// FindNotificationsByMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockNotificationRepository_Expecter) FindNotificationsByMerchant(ctx interface{}, merchantID interface{}, limit interface{}, offset interface{}) *MockNotificationRepository_FindNotificationsByMerchant_Call {
	return &MockNotificationRepository_FindNotificationsByMerchant_Call{Call: _e.mock.On("FindNotificationsByMerchant", ctx, merchantID, limit, offset)}
}

func (_c *MockNotificationRepository_FindNotificationsByMerchant_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, limit int, offset int)) *MockNotificationRepository_FindNotificationsByMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_FindNotificationsByMerchant_Call) Return(merchantLocationNotifications []*entity.MerchantLocationNotification, err error) *MockNotificationRepository_FindNotificationsByMerchant_Call {
	_c.Call.Return(merchantLocationNotifications, err)
	return _c
}

func (_c *MockNotificationRepository_FindNotificationsByMerchant_Call) RunAndReturn(run func(ctx context.Context, merchantID uuid.UUID, limit int, offset int) ([]*entity.MerchantLocationNotification, error)) *MockNotificationRepository_FindNotificationsByMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotificationStatus provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) UpdateNotificationStatus(ctx context.Context, id uuid.UUID, totalSent int, totalFailed int) error {
	ret := _mock.Called(ctx, id, totalSent, totalFailed)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) error); ok {
		r0 = returnFunc(ctx, id, totalSent, totalFailed)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_UpdateNotificationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotificationStatus'
type MockNotificationRepository_UpdateNotificationStatus_Call struct {
	*mock.Call
}

// UpdateNotificationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - totalSent int
//   - totalFailed int
func (_e *MockNotificationRepository_Expecter) UpdateNotificationStatus(ctx interface{}, id interface{}, totalSent interface{}, totalFailed interface{}) *MockNotificationRepository_UpdateNotificationStatus_Call {
	return &MockNotificationRepository_UpdateNotificationStatus_Call{Call: _e.mock.On("UpdateNotificationStatus", ctx, id, totalSent, totalFailed)}
}

func (_c *MockNotificationRepository_UpdateNotificationStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, totalSent int, totalFailed int)) *MockNotificationRepository_UpdateNotificationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_UpdateNotificationStatus_Call) Return(err error) *MockNotificationRepository_UpdateNotificationStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_UpdateNotificationStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, totalSent int, totalFailed int) error) *MockNotificationRepository_UpdateNotificationStatus_Call {
	_c.Call.Return(run)
	return _c
}
