// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"radar/internal/domain/entity"
	"radar/internal/domain/repository"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDiscoveryRepository creates a new instance of MockDiscoveryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiscoveryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiscoveryRepository {
	mock := &MockDiscoveryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDiscoveryRepository is an autogenerated mock type for the DiscoveryRepository type
type MockDiscoveryRepository struct {
	mock.Mock
}

type MockDiscoveryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiscoveryRepository) EXPECT() *MockDiscoveryRepository_Expecter {
	return &MockDiscoveryRepository_Expecter{mock: &_m.Mock}
}

// FindCategoryByID provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) FindCategoryByID(ctx context.Context, id uuid.UUID) (*entity.DiscoveryCategory, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindCategoryByID")
	}

	var r0 *entity.DiscoveryCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.DiscoveryCategory, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.DiscoveryCategory); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DiscoveryCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_FindCategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCategoryByID'
type MockDiscoveryRepository_FindCategoryByID_Call struct {
	*mock.Call
}

// FindCategoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDiscoveryRepository_Expecter) FindCategoryByID(ctx interface{}, id interface{}) *MockDiscoveryRepository_FindCategoryByID_Call {
	return &MockDiscoveryRepository_FindCategoryByID_Call{Call: _e.mock.On("FindCategoryByID", ctx, id)}
}

func (_c *MockDiscoveryRepository_FindCategoryByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDiscoveryRepository_FindCategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_FindCategoryByID_Call) Return(discoveryCategory *entity.DiscoveryCategory, err error) *MockDiscoveryRepository_FindCategoryByID_Call {
	_c.Call.Return(discoveryCategory, err)
	return _c
}

func (_c *MockDiscoveryRepository_FindCategoryByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.DiscoveryCategory, error)) *MockDiscoveryRepository_FindCategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindCategoryBySlug provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) FindCategoryBySlug(ctx context.Context, slug string) (*entity.DiscoveryCategory, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindCategoryBySlug")
	}

	var r0 *entity.DiscoveryCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.DiscoveryCategory, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.DiscoveryCategory); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DiscoveryCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_FindCategoryBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCategoryBySlug'
type MockDiscoveryRepository_FindCategoryBySlug_Call struct {
	*mock.Call
}

// FindCategoryBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockDiscoveryRepository_Expecter) FindCategoryBySlug(ctx interface{}, slug interface{}) *MockDiscoveryRepository_FindCategoryBySlug_Call {
	return &MockDiscoveryRepository_FindCategoryBySlug_Call{Call: _e.mock.On("FindCategoryBySlug", ctx, slug)}
}

func (_c *MockDiscoveryRepository_FindCategoryBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockDiscoveryRepository_FindCategoryBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_FindCategoryBySlug_Call) Return(discoveryCategory *entity.DiscoveryCategory, err error) *MockDiscoveryRepository_FindCategoryBySlug_Call {
	_c.Call.Return(discoveryCategory, err)
	return _c
}

func (_c *MockDiscoveryRepository_FindCategoryBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*entity.DiscoveryCategory, error)) *MockDiscoveryRepository_FindCategoryBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// FindHubByID provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) FindHubByID(ctx context.Context, id uuid.UUID) (*entity.Hub, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindHubByID")
	}

	var r0 *entity.Hub
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Hub, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Hub); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Hub)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_FindHubByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindHubByID'
type MockDiscoveryRepository_FindHubByID_Call struct {
	*mock.Call
}

// FindHubByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDiscoveryRepository_Expecter) FindHubByID(ctx interface{}, id interface{}) *MockDiscoveryRepository_FindHubByID_Call {
	return &MockDiscoveryRepository_FindHubByID_Call{Call: _e.mock.On("FindHubByID", ctx, id)}
}

func (_c *MockDiscoveryRepository_FindHubByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDiscoveryRepository_FindHubByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_FindHubByID_Call) Return(hub *entity.Hub, err error) *MockDiscoveryRepository_FindHubByID_Call {
	_c.Call.Return(hub, err)
	return _c
}

func (_c *MockDiscoveryRepository_FindHubByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Hub, error)) *MockDiscoveryRepository_FindHubByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindHubBySlug provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) FindHubBySlug(ctx context.Context, slug string) (*entity.Hub, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindHubBySlug")
	}

	var r0 *entity.Hub
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Hub, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Hub); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Hub)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_FindHubBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindHubBySlug'
type MockDiscoveryRepository_FindHubBySlug_Call struct {
	*mock.Call
}

// FindHubBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockDiscoveryRepository_Expecter) FindHubBySlug(ctx interface{}, slug interface{}) *MockDiscoveryRepository_FindHubBySlug_Call {
	return &MockDiscoveryRepository_FindHubBySlug_Call{Call: _e.mock.On("FindHubBySlug", ctx, slug)}
}

func (_c *MockDiscoveryRepository_FindHubBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockDiscoveryRepository_FindHubBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_FindHubBySlug_Call) Return(hub *entity.Hub, err error) *MockDiscoveryRepository_FindHubBySlug_Call {
	_c.Call.Return(hub, err)
	return _c
}

func (_c *MockDiscoveryRepository_FindHubBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*entity.Hub, error)) *MockDiscoveryRepository_FindHubBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// FindSubcategoryByID provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) FindSubcategoryByID(ctx context.Context, id uuid.UUID) (*entity.DiscoverySubcategory, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindSubcategoryByID")
	}

	var r0 *entity.DiscoverySubcategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.DiscoverySubcategory, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.DiscoverySubcategory); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DiscoverySubcategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_FindSubcategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSubcategoryByID'
type MockDiscoveryRepository_FindSubcategoryByID_Call struct {
	*mock.Call
}

// FindSubcategoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDiscoveryRepository_Expecter) FindSubcategoryByID(ctx interface{}, id interface{}) *MockDiscoveryRepository_FindSubcategoryByID_Call {
	return &MockDiscoveryRepository_FindSubcategoryByID_Call{Call: _e.mock.On("FindSubcategoryByID", ctx, id)}
}

func (_c *MockDiscoveryRepository_FindSubcategoryByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDiscoveryRepository_FindSubcategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_FindSubcategoryByID_Call) Return(discoverySubcategory *entity.DiscoverySubcategory, err error) *MockDiscoveryRepository_FindSubcategoryByID_Call {
	_c.Call.Return(discoverySubcategory, err)
	return _c
}

func (_c *MockDiscoveryRepository_FindSubcategoryByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.DiscoverySubcategory, error)) *MockDiscoveryRepository_FindSubcategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSubcategoryBySlug provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) FindSubcategoryBySlug(ctx context.Context, slug string) (*entity.DiscoverySubcategory, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindSubcategoryBySlug")
	}

	var r0 *entity.DiscoverySubcategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.DiscoverySubcategory, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.DiscoverySubcategory); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DiscoverySubcategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_FindSubcategoryBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSubcategoryBySlug'
type MockDiscoveryRepository_FindSubcategoryBySlug_Call struct {
	*mock.Call
}

// FindSubcategoryBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockDiscoveryRepository_Expecter) FindSubcategoryBySlug(ctx interface{}, slug interface{}) *MockDiscoveryRepository_FindSubcategoryBySlug_Call {
	return &MockDiscoveryRepository_FindSubcategoryBySlug_Call{Call: _e.mock.On("FindSubcategoryBySlug", ctx, slug)}
}

func (_c *MockDiscoveryRepository_FindSubcategoryBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockDiscoveryRepository_FindSubcategoryBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_FindSubcategoryBySlug_Call) Return(discoverySubcategory *entity.DiscoverySubcategory, err error) *MockDiscoveryRepository_FindSubcategoryBySlug_Call {
	_c.Call.Return(discoverySubcategory, err)
	return _c
}

func (_c *MockDiscoveryRepository_FindSubcategoryBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*entity.DiscoverySubcategory, error)) *MockDiscoveryRepository_FindSubcategoryBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveCategories provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) ListActiveCategories(ctx context.Context) ([]*entity.DiscoveryCategory, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveCategories")
	}

	var r0 []*entity.DiscoveryCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.DiscoveryCategory, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.DiscoveryCategory); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.DiscoveryCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_ListActiveCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveCategories'
type MockDiscoveryRepository_ListActiveCategories_Call struct {
	*mock.Call
}

// ListActiveCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDiscoveryRepository_Expecter) ListActiveCategories(ctx interface{}) *MockDiscoveryRepository_ListActiveCategories_Call {
	return &MockDiscoveryRepository_ListActiveCategories_Call{Call: _e.mock.On("ListActiveCategories", ctx)}
}

func (_c *MockDiscoveryRepository_ListActiveCategories_Call) Run(run func(ctx context.Context)) *MockDiscoveryRepository_ListActiveCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_ListActiveCategories_Call) Return(discoveryCategorys []*entity.DiscoveryCategory, err error) *MockDiscoveryRepository_ListActiveCategories_Call {
	_c.Call.Return(discoveryCategorys, err)
	return _c
}

func (_c *MockDiscoveryRepository_ListActiveCategories_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.DiscoveryCategory, error)) *MockDiscoveryRepository_ListActiveCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveHubs provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) ListActiveHubs(ctx context.Context) ([]*entity.Hub, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveHubs")
	}

	var r0 []*entity.Hub
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Hub, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Hub); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Hub)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_ListActiveHubs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveHubs'
type MockDiscoveryRepository_ListActiveHubs_Call struct {
	*mock.Call
}

// ListActiveHubs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDiscoveryRepository_Expecter) ListActiveHubs(ctx interface{}) *MockDiscoveryRepository_ListActiveHubs_Call {
	return &MockDiscoveryRepository_ListActiveHubs_Call{Call: _e.mock.On("ListActiveHubs", ctx)}
}

func (_c *MockDiscoveryRepository_ListActiveHubs_Call) Run(run func(ctx context.Context)) *MockDiscoveryRepository_ListActiveHubs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_ListActiveHubs_Call) Return(hubs []*entity.Hub, err error) *MockDiscoveryRepository_ListActiveHubs_Call {
	_c.Call.Return(hubs, err)
	return _c
}

func (_c *MockDiscoveryRepository_ListActiveHubs_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Hub, error)) *MockDiscoveryRepository_ListActiveHubs_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveSubcategories provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) ListActiveSubcategories(ctx context.Context) ([]*entity.DiscoverySubcategory, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveSubcategories")
	}

	var r0 []*entity.DiscoverySubcategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.DiscoverySubcategory, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.DiscoverySubcategory); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.DiscoverySubcategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiscoveryRepository_ListActiveSubcategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveSubcategories'
type MockDiscoveryRepository_ListActiveSubcategories_Call struct {
	*mock.Call
}

// ListActiveSubcategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDiscoveryRepository_Expecter) ListActiveSubcategories(ctx interface{}) *MockDiscoveryRepository_ListActiveSubcategories_Call {
	return &MockDiscoveryRepository_ListActiveSubcategories_Call{Call: _e.mock.On("ListActiveSubcategories", ctx)}
}

func (_c *MockDiscoveryRepository_ListActiveSubcategories_Call) Run(run func(ctx context.Context)) *MockDiscoveryRepository_ListActiveSubcategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_ListActiveSubcategories_Call) Return(discoverySubcategorys []*entity.DiscoverySubcategory, err error) *MockDiscoveryRepository_ListActiveSubcategories_Call {
	_c.Call.Return(discoverySubcategorys, err)
	return _c
}

func (_c *MockDiscoveryRepository_ListActiveSubcategories_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.DiscoverySubcategory, error)) *MockDiscoveryRepository_ListActiveSubcategories_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPublicMerchants provides a mock function for the type MockDiscoveryRepository
func (_mock *MockDiscoveryRepository) SearchPublicMerchants(ctx context.Context, filter *repository.PublicMerchantSearchFilter) ([]*entity.PublicMerchantSearchItem, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchPublicMerchants")
	}

	var r0 []*entity.PublicMerchantSearchItem
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.PublicMerchantSearchFilter) ([]*entity.PublicMerchantSearchItem, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.PublicMerchantSearchFilter) []*entity.PublicMerchantSearchItem); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PublicMerchantSearchItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repository.PublicMerchantSearchFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *repository.PublicMerchantSearchFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDiscoveryRepository_SearchPublicMerchants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPublicMerchants'
type MockDiscoveryRepository_SearchPublicMerchants_Call struct {
	*mock.Call
}

// SearchPublicMerchants is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *repository.PublicMerchantSearchFilter
func (_e *MockDiscoveryRepository_Expecter) SearchPublicMerchants(ctx interface{}, filter interface{}) *MockDiscoveryRepository_SearchPublicMerchants_Call {
	return &MockDiscoveryRepository_SearchPublicMerchants_Call{Call: _e.mock.On("SearchPublicMerchants", ctx, filter)}
}

func (_c *MockDiscoveryRepository_SearchPublicMerchants_Call) Run(run func(ctx context.Context, filter *repository.PublicMerchantSearchFilter)) *MockDiscoveryRepository_SearchPublicMerchants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.PublicMerchantSearchFilter
		if args[1] != nil {
			arg1 = args[1].(*repository.PublicMerchantSearchFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDiscoveryRepository_SearchPublicMerchants_Call) Return(publicMerchantSearchItems []*entity.PublicMerchantSearchItem, n int64, err error) *MockDiscoveryRepository_SearchPublicMerchants_Call {
	_c.Call.Return(publicMerchantSearchItems, n, err)
	return _c
}

func (_c *MockDiscoveryRepository_SearchPublicMerchants_Call) RunAndReturn(run func(ctx context.Context, filter *repository.PublicMerchantSearchFilter) ([]*entity.PublicMerchantSearchItem, int64, error)) *MockDiscoveryRepository_SearchPublicMerchants_Call {
	_c.Call.Return(run)
	return _c
}
