// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"radar/internal/domain/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionManager creates a new instance of MockTransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManager {
	mock := &MockTransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionManager is an autogenerated mock type for the TransactionManager type
type MockTransactionManager struct {
	mock.Mock
}

type MockTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManager) EXPECT() *MockTransactionManager_Expecter {
	return &MockTransactionManager_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) Execute(ctx context.Context, fn func(txRepoFactory repository.RepositoryFactory) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(txRepoFactory repository.RepositoryFactory) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTransactionManager_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(txRepoFactory repository.RepositoryFactory) error
func (_e *MockTransactionManager_Expecter) Execute(ctx interface{}, fn interface{}) *MockTransactionManager_Execute_Call {
	return &MockTransactionManager_Execute_Call{Call: _e.mock.On("Execute", ctx, fn)}
}

func (_c *MockTransactionManager_Execute_Call) Run(run func(ctx context.Context, fn func(txRepoFactory repository.RepositoryFactory) error)) *MockTransactionManager_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(txRepoFactory repository.RepositoryFactory) error
		if args[1] != nil {
			arg1 = args[1].(func(txRepoFactory repository.RepositoryFactory) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionManager_Execute_Call) Return(err error) *MockTransactionManager_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_Execute_Call) RunAndReturn(run func(ctx context.Context, fn func(txRepoFactory repository.RepositoryFactory) error) error) *MockTransactionManager_Execute_Call {
	_c.Call.Return(run)
	return _c
}
