apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../shared/radar

patches:
  - target:
      kind: Service
      name: radar
    patch: |-
      - op: add
        path: /metadata/annotations/run.googleapis.com~1invoker-iam-disabled
        value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: HTTP_CLOUDFLARESECRET
          value: HTTP_CLOUDFLARESECRET_PLACEHOLDER
