// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newDiscoverySubcategoryModel(db *gorm.DB, opts ...gen.DOOption) discoverySubcategoryModel {
	_discoverySubcategoryModel := discoverySubcategoryModel{}

	_discoverySubcategoryModel.discoverySubcategoryModelDo.UseDB(db, opts...)
	_discoverySubcategoryModel.discoverySubcategoryModelDo.UseModel(&model.DiscoverySubcategoryModel{})

	tableName := _discoverySubcategoryModel.discoverySubcategoryModelDo.TableName()
	_discoverySubcategoryModel.ALL = field.NewAsterisk(tableName)
	_discoverySubcategoryModel.ID = field.NewField(tableName, "id")
	_discoverySubcategoryModel.CategoryID = field.NewField(tableName, "category_id")
	_discoverySubcategoryModel.Slug = field.NewString(tableName, "slug")
	_discoverySubcategoryModel.Name = field.NewString(tableName, "name")
	_discoverySubcategoryModel.DisplayOrder = field.NewInt(tableName, "display_order")
	_discoverySubcategoryModel.Status = field.NewString(tableName, "status")
	_discoverySubcategoryModel.CreatedAt = field.NewTime(tableName, "created_at")
	_discoverySubcategoryModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_discoverySubcategoryModel.Category = discoverySubcategoryModelBelongsToCategory{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Category", "model.DiscoveryCategoryModel"),
		Subcategories: struct {
			field.RelationField
			Category struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Category.Subcategories", "model.DiscoverySubcategoryModel"),
			Category: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Category.Subcategories.Category", "model.DiscoveryCategoryModel"),
			},
		},
	}

	_discoverySubcategoryModel.fillFieldMap()

	return _discoverySubcategoryModel
}

type discoverySubcategoryModel struct {
	discoverySubcategoryModelDo discoverySubcategoryModelDo

	ALL          field.Asterisk
	ID           field.Field
	CategoryID   field.Field
	Slug         field.String
	Name         field.String
	DisplayOrder field.Int
	Status       field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Category     discoverySubcategoryModelBelongsToCategory

	fieldMap map[string]field.Expr
}

func (d discoverySubcategoryModel) Table(newTableName string) *discoverySubcategoryModel {
	d.discoverySubcategoryModelDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d discoverySubcategoryModel) As(alias string) *discoverySubcategoryModel {
	d.discoverySubcategoryModelDo.DO = *(d.discoverySubcategoryModelDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *discoverySubcategoryModel) updateTableName(table string) *discoverySubcategoryModel {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewField(table, "id")
	d.CategoryID = field.NewField(table, "category_id")
	d.Slug = field.NewString(table, "slug")
	d.Name = field.NewString(table, "name")
	d.DisplayOrder = field.NewInt(table, "display_order")
	d.Status = field.NewString(table, "status")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *discoverySubcategoryModel) WithContext(ctx context.Context) *discoverySubcategoryModelDo {
	return d.discoverySubcategoryModelDo.WithContext(ctx)
}

func (d discoverySubcategoryModel) TableName() string {
	return d.discoverySubcategoryModelDo.TableName()
}

func (d discoverySubcategoryModel) Alias() string { return d.discoverySubcategoryModelDo.Alias() }

func (d discoverySubcategoryModel) Columns(cols ...field.Expr) gen.Columns {
	return d.discoverySubcategoryModelDo.Columns(cols...)
}

func (d *discoverySubcategoryModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *discoverySubcategoryModel) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["category_id"] = d.CategoryID
	d.fieldMap["slug"] = d.Slug
	d.fieldMap["name"] = d.Name
	d.fieldMap["display_order"] = d.DisplayOrder
	d.fieldMap["status"] = d.Status
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt

}

func (d discoverySubcategoryModel) clone(db *gorm.DB) discoverySubcategoryModel {
	d.discoverySubcategoryModelDo.ReplaceConnPool(db.Statement.ConnPool)
	d.Category.db = db.Session(&gorm.Session{Initialized: true})
	d.Category.db.Statement.ConnPool = db.Statement.ConnPool
	return d
}

func (d discoverySubcategoryModel) replaceDB(db *gorm.DB) discoverySubcategoryModel {
	d.discoverySubcategoryModelDo.ReplaceDB(db)
	d.Category.db = db.Session(&gorm.Session{})
	return d
}

type discoverySubcategoryModelBelongsToCategory struct {
	db *gorm.DB

	field.RelationField

	Subcategories struct {
		field.RelationField
		Category struct {
			field.RelationField
		}
	}
}

func (a discoverySubcategoryModelBelongsToCategory) Where(conds ...field.Expr) *discoverySubcategoryModelBelongsToCategory {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a discoverySubcategoryModelBelongsToCategory) WithContext(ctx context.Context) *discoverySubcategoryModelBelongsToCategory {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a discoverySubcategoryModelBelongsToCategory) Session(session *gorm.Session) *discoverySubcategoryModelBelongsToCategory {
	a.db = a.db.Session(session)
	return &a
}

func (a discoverySubcategoryModelBelongsToCategory) Model(m *model.DiscoverySubcategoryModel) *discoverySubcategoryModelBelongsToCategoryTx {
	return &discoverySubcategoryModelBelongsToCategoryTx{a.db.Model(m).Association(a.Name())}
}

func (a discoverySubcategoryModelBelongsToCategory) Unscoped() *discoverySubcategoryModelBelongsToCategory {
	a.db = a.db.Unscoped()
	return &a
}

type discoverySubcategoryModelBelongsToCategoryTx struct{ tx *gorm.Association }

func (a discoverySubcategoryModelBelongsToCategoryTx) Find() (result *model.DiscoveryCategoryModel, err error) {
	return result, a.tx.Find(&result)
}

func (a discoverySubcategoryModelBelongsToCategoryTx) Append(values ...*model.DiscoveryCategoryModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a discoverySubcategoryModelBelongsToCategoryTx) Replace(values ...*model.DiscoveryCategoryModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a discoverySubcategoryModelBelongsToCategoryTx) Delete(values ...*model.DiscoveryCategoryModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a discoverySubcategoryModelBelongsToCategoryTx) Clear() error {
	return a.tx.Clear()
}

func (a discoverySubcategoryModelBelongsToCategoryTx) Count() int64 {
	return a.tx.Count()
}

func (a discoverySubcategoryModelBelongsToCategoryTx) Unscoped() *discoverySubcategoryModelBelongsToCategoryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type discoverySubcategoryModelDo struct{ gen.DO }

func (d discoverySubcategoryModelDo) Debug() *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Debug())
}

func (d discoverySubcategoryModelDo) WithContext(ctx context.Context) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d discoverySubcategoryModelDo) ReadDB() *discoverySubcategoryModelDo {
	return d.Clauses(dbresolver.Read)
}

func (d discoverySubcategoryModelDo) WriteDB() *discoverySubcategoryModelDo {
	return d.Clauses(dbresolver.Write)
}

func (d discoverySubcategoryModelDo) Session(config *gorm.Session) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Session(config))
}

func (d discoverySubcategoryModelDo) Clauses(conds ...clause.Expression) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d discoverySubcategoryModelDo) Returning(value interface{}, columns ...string) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d discoverySubcategoryModelDo) Not(conds ...gen.Condition) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d discoverySubcategoryModelDo) Or(conds ...gen.Condition) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d discoverySubcategoryModelDo) Select(conds ...field.Expr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d discoverySubcategoryModelDo) Where(conds ...gen.Condition) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d discoverySubcategoryModelDo) Order(conds ...field.Expr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d discoverySubcategoryModelDo) Distinct(cols ...field.Expr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d discoverySubcategoryModelDo) Omit(cols ...field.Expr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d discoverySubcategoryModelDo) Join(table schema.Tabler, on ...field.Expr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d discoverySubcategoryModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d discoverySubcategoryModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d discoverySubcategoryModelDo) Group(cols ...field.Expr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d discoverySubcategoryModelDo) Having(conds ...gen.Condition) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d discoverySubcategoryModelDo) Limit(limit int) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d discoverySubcategoryModelDo) Offset(offset int) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d discoverySubcategoryModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d discoverySubcategoryModelDo) Unscoped() *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Unscoped())
}

func (d discoverySubcategoryModelDo) Create(values ...*model.DiscoverySubcategoryModel) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d discoverySubcategoryModelDo) CreateInBatches(values []*model.DiscoverySubcategoryModel, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d discoverySubcategoryModelDo) Save(values ...*model.DiscoverySubcategoryModel) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d discoverySubcategoryModelDo) First() (*model.DiscoverySubcategoryModel, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoverySubcategoryModel), nil
	}
}

func (d discoverySubcategoryModelDo) Take() (*model.DiscoverySubcategoryModel, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoverySubcategoryModel), nil
	}
}

func (d discoverySubcategoryModelDo) Last() (*model.DiscoverySubcategoryModel, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoverySubcategoryModel), nil
	}
}

func (d discoverySubcategoryModelDo) Find() ([]*model.DiscoverySubcategoryModel, error) {
	result, err := d.DO.Find()
	return result.([]*model.DiscoverySubcategoryModel), err
}

func (d discoverySubcategoryModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DiscoverySubcategoryModel, err error) {
	buf := make([]*model.DiscoverySubcategoryModel, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d discoverySubcategoryModelDo) FindInBatches(result *[]*model.DiscoverySubcategoryModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d discoverySubcategoryModelDo) Attrs(attrs ...field.AssignExpr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d discoverySubcategoryModelDo) Assign(attrs ...field.AssignExpr) *discoverySubcategoryModelDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d discoverySubcategoryModelDo) Joins(fields ...field.RelationField) *discoverySubcategoryModelDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d discoverySubcategoryModelDo) Preload(fields ...field.RelationField) *discoverySubcategoryModelDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d discoverySubcategoryModelDo) FirstOrInit() (*model.DiscoverySubcategoryModel, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoverySubcategoryModel), nil
	}
}

func (d discoverySubcategoryModelDo) FirstOrCreate() (*model.DiscoverySubcategoryModel, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoverySubcategoryModel), nil
	}
}

func (d discoverySubcategoryModelDo) FindByPage(offset int, limit int) (result []*model.DiscoverySubcategoryModel, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d discoverySubcategoryModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d discoverySubcategoryModelDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d discoverySubcategoryModelDo) Delete(models ...*model.DiscoverySubcategoryModel) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *discoverySubcategoryModelDo) withDO(do gen.Dao) *discoverySubcategoryModelDo {
	d.DO = *do.(*gen.DO)
	return d
}
