// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newDiscoveryCategoryModel(db *gorm.DB, opts ...gen.DOOption) discoveryCategoryModel {
	_discoveryCategoryModel := discoveryCategoryModel{}

	_discoveryCategoryModel.discoveryCategoryModelDo.UseDB(db, opts...)
	_discoveryCategoryModel.discoveryCategoryModelDo.UseModel(&model.DiscoveryCategoryModel{})

	tableName := _discoveryCategoryModel.discoveryCategoryModelDo.TableName()
	_discoveryCategoryModel.ALL = field.NewAsterisk(tableName)
	_discoveryCategoryModel.ID = field.NewField(tableName, "id")
	_discoveryCategoryModel.Slug = field.NewString(tableName, "slug")
	_discoveryCategoryModel.Name = field.NewString(tableName, "name")
	_discoveryCategoryModel.DisplayOrder = field.NewInt(tableName, "display_order")
	_discoveryCategoryModel.Status = field.NewString(tableName, "status")
	_discoveryCategoryModel.CreatedAt = field.NewTime(tableName, "created_at")
	_discoveryCategoryModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_discoveryCategoryModel.Subcategories = discoveryCategoryModelHasManySubcategories{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Subcategories", "model.DiscoverySubcategoryModel"),
		Category: struct {
			field.RelationField
			Subcategories struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Subcategories.Category", "model.DiscoveryCategoryModel"),
			Subcategories: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Subcategories.Category.Subcategories", "model.DiscoverySubcategoryModel"),
			},
		},
	}

	_discoveryCategoryModel.fillFieldMap()

	return _discoveryCategoryModel
}

type discoveryCategoryModel struct {
	discoveryCategoryModelDo discoveryCategoryModelDo

	ALL           field.Asterisk
	ID            field.Field
	Slug          field.String
	Name          field.String
	DisplayOrder  field.Int
	Status        field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time
	Subcategories discoveryCategoryModelHasManySubcategories

	fieldMap map[string]field.Expr
}

func (d discoveryCategoryModel) Table(newTableName string) *discoveryCategoryModel {
	d.discoveryCategoryModelDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d discoveryCategoryModel) As(alias string) *discoveryCategoryModel {
	d.discoveryCategoryModelDo.DO = *(d.discoveryCategoryModelDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *discoveryCategoryModel) updateTableName(table string) *discoveryCategoryModel {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewField(table, "id")
	d.Slug = field.NewString(table, "slug")
	d.Name = field.NewString(table, "name")
	d.DisplayOrder = field.NewInt(table, "display_order")
	d.Status = field.NewString(table, "status")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *discoveryCategoryModel) WithContext(ctx context.Context) *discoveryCategoryModelDo {
	return d.discoveryCategoryModelDo.WithContext(ctx)
}

func (d discoveryCategoryModel) TableName() string { return d.discoveryCategoryModelDo.TableName() }

func (d discoveryCategoryModel) Alias() string { return d.discoveryCategoryModelDo.Alias() }

func (d discoveryCategoryModel) Columns(cols ...field.Expr) gen.Columns {
	return d.discoveryCategoryModelDo.Columns(cols...)
}

func (d *discoveryCategoryModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *discoveryCategoryModel) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["id"] = d.ID
	d.fieldMap["slug"] = d.Slug
	d.fieldMap["name"] = d.Name
	d.fieldMap["display_order"] = d.DisplayOrder
	d.fieldMap["status"] = d.Status
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt

}

func (d discoveryCategoryModel) clone(db *gorm.DB) discoveryCategoryModel {
	d.discoveryCategoryModelDo.ReplaceConnPool(db.Statement.ConnPool)
	d.Subcategories.db = db.Session(&gorm.Session{Initialized: true})
	d.Subcategories.db.Statement.ConnPool = db.Statement.ConnPool
	return d
}

func (d discoveryCategoryModel) replaceDB(db *gorm.DB) discoveryCategoryModel {
	d.discoveryCategoryModelDo.ReplaceDB(db)
	d.Subcategories.db = db.Session(&gorm.Session{})
	return d
}

type discoveryCategoryModelHasManySubcategories struct {
	db *gorm.DB

	field.RelationField

	Category struct {
		field.RelationField
		Subcategories struct {
			field.RelationField
		}
	}
}

func (a discoveryCategoryModelHasManySubcategories) Where(conds ...field.Expr) *discoveryCategoryModelHasManySubcategories {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a discoveryCategoryModelHasManySubcategories) WithContext(ctx context.Context) *discoveryCategoryModelHasManySubcategories {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a discoveryCategoryModelHasManySubcategories) Session(session *gorm.Session) *discoveryCategoryModelHasManySubcategories {
	a.db = a.db.Session(session)
	return &a
}

func (a discoveryCategoryModelHasManySubcategories) Model(m *model.DiscoveryCategoryModel) *discoveryCategoryModelHasManySubcategoriesTx {
	return &discoveryCategoryModelHasManySubcategoriesTx{a.db.Model(m).Association(a.Name())}
}

func (a discoveryCategoryModelHasManySubcategories) Unscoped() *discoveryCategoryModelHasManySubcategories {
	a.db = a.db.Unscoped()
	return &a
}

type discoveryCategoryModelHasManySubcategoriesTx struct{ tx *gorm.Association }

func (a discoveryCategoryModelHasManySubcategoriesTx) Find() (result []*model.DiscoverySubcategoryModel, err error) {
	return result, a.tx.Find(&result)
}

func (a discoveryCategoryModelHasManySubcategoriesTx) Append(values ...*model.DiscoverySubcategoryModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a discoveryCategoryModelHasManySubcategoriesTx) Replace(values ...*model.DiscoverySubcategoryModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a discoveryCategoryModelHasManySubcategoriesTx) Delete(values ...*model.DiscoverySubcategoryModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a discoveryCategoryModelHasManySubcategoriesTx) Clear() error {
	return a.tx.Clear()
}

func (a discoveryCategoryModelHasManySubcategoriesTx) Count() int64 {
	return a.tx.Count()
}

func (a discoveryCategoryModelHasManySubcategoriesTx) Unscoped() *discoveryCategoryModelHasManySubcategoriesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type discoveryCategoryModelDo struct{ gen.DO }

func (d discoveryCategoryModelDo) Debug() *discoveryCategoryModelDo {
	return d.withDO(d.DO.Debug())
}

func (d discoveryCategoryModelDo) WithContext(ctx context.Context) *discoveryCategoryModelDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d discoveryCategoryModelDo) ReadDB() *discoveryCategoryModelDo {
	return d.Clauses(dbresolver.Read)
}

func (d discoveryCategoryModelDo) WriteDB() *discoveryCategoryModelDo {
	return d.Clauses(dbresolver.Write)
}

func (d discoveryCategoryModelDo) Session(config *gorm.Session) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Session(config))
}

func (d discoveryCategoryModelDo) Clauses(conds ...clause.Expression) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d discoveryCategoryModelDo) Returning(value interface{}, columns ...string) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d discoveryCategoryModelDo) Not(conds ...gen.Condition) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d discoveryCategoryModelDo) Or(conds ...gen.Condition) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d discoveryCategoryModelDo) Select(conds ...field.Expr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d discoveryCategoryModelDo) Where(conds ...gen.Condition) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d discoveryCategoryModelDo) Order(conds ...field.Expr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d discoveryCategoryModelDo) Distinct(cols ...field.Expr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d discoveryCategoryModelDo) Omit(cols ...field.Expr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d discoveryCategoryModelDo) Join(table schema.Tabler, on ...field.Expr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d discoveryCategoryModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d discoveryCategoryModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d discoveryCategoryModelDo) Group(cols ...field.Expr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d discoveryCategoryModelDo) Having(conds ...gen.Condition) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d discoveryCategoryModelDo) Limit(limit int) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d discoveryCategoryModelDo) Offset(offset int) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d discoveryCategoryModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d discoveryCategoryModelDo) Unscoped() *discoveryCategoryModelDo {
	return d.withDO(d.DO.Unscoped())
}

func (d discoveryCategoryModelDo) Create(values ...*model.DiscoveryCategoryModel) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d discoveryCategoryModelDo) CreateInBatches(values []*model.DiscoveryCategoryModel, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d discoveryCategoryModelDo) Save(values ...*model.DiscoveryCategoryModel) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d discoveryCategoryModelDo) First() (*model.DiscoveryCategoryModel, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoveryCategoryModel), nil
	}
}

func (d discoveryCategoryModelDo) Take() (*model.DiscoveryCategoryModel, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoveryCategoryModel), nil
	}
}

func (d discoveryCategoryModelDo) Last() (*model.DiscoveryCategoryModel, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoveryCategoryModel), nil
	}
}

func (d discoveryCategoryModelDo) Find() ([]*model.DiscoveryCategoryModel, error) {
	result, err := d.DO.Find()
	return result.([]*model.DiscoveryCategoryModel), err
}

func (d discoveryCategoryModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DiscoveryCategoryModel, err error) {
	buf := make([]*model.DiscoveryCategoryModel, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d discoveryCategoryModelDo) FindInBatches(result *[]*model.DiscoveryCategoryModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d discoveryCategoryModelDo) Attrs(attrs ...field.AssignExpr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d discoveryCategoryModelDo) Assign(attrs ...field.AssignExpr) *discoveryCategoryModelDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d discoveryCategoryModelDo) Joins(fields ...field.RelationField) *discoveryCategoryModelDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d discoveryCategoryModelDo) Preload(fields ...field.RelationField) *discoveryCategoryModelDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d discoveryCategoryModelDo) FirstOrInit() (*model.DiscoveryCategoryModel, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoveryCategoryModel), nil
	}
}

func (d discoveryCategoryModelDo) FirstOrCreate() (*model.DiscoveryCategoryModel, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscoveryCategoryModel), nil
	}
}

func (d discoveryCategoryModelDo) FindByPage(offset int, limit int) (result []*model.DiscoveryCategoryModel, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d discoveryCategoryModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d discoveryCategoryModelDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d discoveryCategoryModelDo) Delete(models ...*model.DiscoveryCategoryModel) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *discoveryCategoryModelDo) withDO(do gen.Dao) *discoveryCategoryModelDo {
	d.DO = *do.(*gen.DO)
	return d
}
