// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newHubModel(db *gorm.DB, opts ...gen.DOOption) hubModel {
	_hubModel := hubModel{}

	_hubModel.hubModelDo.UseDB(db, opts...)
	_hubModel.hubModelDo.UseModel(&model.HubModel{})

	tableName := _hubModel.hubModelDo.TableName()
	_hubModel.ALL = field.NewAsterisk(tableName)
	_hubModel.ID = field.NewField(tableName, "id")
	_hubModel.Slug = field.NewString(tableName, "slug")
	_hubModel.Name = field.NewString(tableName, "name")
	_hubModel.Type = field.NewString(tableName, "type")
	_hubModel.City = field.NewString(tableName, "city")
	_hubModel.AreaName = field.NewString(tableName, "area_name")
	_hubModel.StartsAt = field.NewTime(tableName, "starts_at")
	_hubModel.EndsAt = field.NewTime(tableName, "ends_at")
	_hubModel.Status = field.NewString(tableName, "status")
	_hubModel.CreatedAt = field.NewTime(tableName, "created_at")
	_hubModel.UpdatedAt = field.NewTime(tableName, "updated_at")

	_hubModel.fillFieldMap()

	return _hubModel
}

type hubModel struct {
	hubModelDo hubModelDo

	ALL       field.Asterisk
	ID        field.Field
	Slug      field.String
	Name      field.String
	Type      field.String
	City      field.String
	AreaName  field.String
	StartsAt  field.Time
	EndsAt    field.Time
	Status    field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (h hubModel) Table(newTableName string) *hubModel {
	h.hubModelDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hubModel) As(alias string) *hubModel {
	h.hubModelDo.DO = *(h.hubModelDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hubModel) updateTableName(table string) *hubModel {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewField(table, "id")
	h.Slug = field.NewString(table, "slug")
	h.Name = field.NewString(table, "name")
	h.Type = field.NewString(table, "type")
	h.City = field.NewString(table, "city")
	h.AreaName = field.NewString(table, "area_name")
	h.StartsAt = field.NewTime(table, "starts_at")
	h.EndsAt = field.NewTime(table, "ends_at")
	h.Status = field.NewString(table, "status")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.UpdatedAt = field.NewTime(table, "updated_at")

	h.fillFieldMap()

	return h
}

func (h *hubModel) WithContext(ctx context.Context) *hubModelDo { return h.hubModelDo.WithContext(ctx) }

func (h hubModel) TableName() string { return h.hubModelDo.TableName() }

func (h hubModel) Alias() string { return h.hubModelDo.Alias() }

func (h hubModel) Columns(cols ...field.Expr) gen.Columns { return h.hubModelDo.Columns(cols...) }

func (h *hubModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hubModel) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 11)
	h.fieldMap["id"] = h.ID
	h.fieldMap["slug"] = h.Slug
	h.fieldMap["name"] = h.Name
	h.fieldMap["type"] = h.Type
	h.fieldMap["city"] = h.City
	h.fieldMap["area_name"] = h.AreaName
	h.fieldMap["starts_at"] = h.StartsAt
	h.fieldMap["ends_at"] = h.EndsAt
	h.fieldMap["status"] = h.Status
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
}

func (h hubModel) clone(db *gorm.DB) hubModel {
	h.hubModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hubModel) replaceDB(db *gorm.DB) hubModel {
	h.hubModelDo.ReplaceDB(db)
	return h
}

type hubModelDo struct{ gen.DO }

func (h hubModelDo) Debug() *hubModelDo {
	return h.withDO(h.DO.Debug())
}

func (h hubModelDo) WithContext(ctx context.Context) *hubModelDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hubModelDo) ReadDB() *hubModelDo {
	return h.Clauses(dbresolver.Read)
}

func (h hubModelDo) WriteDB() *hubModelDo {
	return h.Clauses(dbresolver.Write)
}

func (h hubModelDo) Session(config *gorm.Session) *hubModelDo {
	return h.withDO(h.DO.Session(config))
}

func (h hubModelDo) Clauses(conds ...clause.Expression) *hubModelDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hubModelDo) Returning(value interface{}, columns ...string) *hubModelDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hubModelDo) Not(conds ...gen.Condition) *hubModelDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hubModelDo) Or(conds ...gen.Condition) *hubModelDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hubModelDo) Select(conds ...field.Expr) *hubModelDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hubModelDo) Where(conds ...gen.Condition) *hubModelDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hubModelDo) Order(conds ...field.Expr) *hubModelDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hubModelDo) Distinct(cols ...field.Expr) *hubModelDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hubModelDo) Omit(cols ...field.Expr) *hubModelDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hubModelDo) Join(table schema.Tabler, on ...field.Expr) *hubModelDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hubModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *hubModelDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hubModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *hubModelDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hubModelDo) Group(cols ...field.Expr) *hubModelDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hubModelDo) Having(conds ...gen.Condition) *hubModelDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hubModelDo) Limit(limit int) *hubModelDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hubModelDo) Offset(offset int) *hubModelDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hubModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *hubModelDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hubModelDo) Unscoped() *hubModelDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hubModelDo) Create(values ...*model.HubModel) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hubModelDo) CreateInBatches(values []*model.HubModel, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hubModelDo) Save(values ...*model.HubModel) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hubModelDo) First() (*model.HubModel, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HubModel), nil
	}
}

func (h hubModelDo) Take() (*model.HubModel, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HubModel), nil
	}
}

func (h hubModelDo) Last() (*model.HubModel, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HubModel), nil
	}
}

func (h hubModelDo) Find() ([]*model.HubModel, error) {
	result, err := h.DO.Find()
	return result.([]*model.HubModel), err
}

func (h hubModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HubModel, err error) {
	buf := make([]*model.HubModel, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hubModelDo) FindInBatches(result *[]*model.HubModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hubModelDo) Attrs(attrs ...field.AssignExpr) *hubModelDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hubModelDo) Assign(attrs ...field.AssignExpr) *hubModelDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hubModelDo) Joins(fields ...field.RelationField) *hubModelDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hubModelDo) Preload(fields ...field.RelationField) *hubModelDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hubModelDo) FirstOrInit() (*model.HubModel, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HubModel), nil
	}
}

func (h hubModelDo) FirstOrCreate() (*model.HubModel, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HubModel), nil
	}
}

func (h hubModelDo) FindByPage(offset int, limit int) (result []*model.HubModel, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hubModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hubModelDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hubModelDo) Delete(models ...*model.HubModel) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hubModelDo) withDO(do gen.Dao) *hubModelDo {
	h.DO = *do.(*gen.DO)
	return h
}
