// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newLoginAttemptModel(db *gorm.DB, opts ...gen.DOOption) loginAttemptModel {
	_loginAttemptModel := loginAttemptModel{}

	_loginAttemptModel.loginAttemptModelDo.UseDB(db, opts...)
	_loginAttemptModel.loginAttemptModelDo.UseModel(&model.LoginAttemptModel{})

	tableName := _loginAttemptModel.loginAttemptModelDo.TableName()
	_loginAttemptModel.ALL = field.NewAsterisk(tableName)
	_loginAttemptModel.ID = field.NewField(tableName, "id")
	_loginAttemptModel.AttemptKey = field.NewString(tableName, "attempt_key")
	_loginAttemptModel.UserID = field.NewField(tableName, "user_id")
	_loginAttemptModel.FailedCount = field.NewInt(tableName, "failed_count")
	_loginAttemptModel.LockoutCount = field.NewInt(tableName, "lockout_count")
	_loginAttemptModel.LockedUntil = field.NewTime(tableName, "locked_until")
	_loginAttemptModel.LastFailedAt = field.NewTime(tableName, "last_failed_at")
	_loginAttemptModel.LastLockoutAt = field.NewTime(tableName, "last_lockout_at")
	_loginAttemptModel.CreatedAt = field.NewTime(tableName, "created_at")
	_loginAttemptModel.UpdatedAt = field.NewTime(tableName, "updated_at")

	_loginAttemptModel.fillFieldMap()

	return _loginAttemptModel
}

type loginAttemptModel struct {
	loginAttemptModelDo loginAttemptModelDo

	ALL           field.Asterisk
	ID            field.Field
	AttemptKey    field.String
	UserID        field.Field
	FailedCount   field.Int
	LockoutCount  field.Int
	LockedUntil   field.Time
	LastFailedAt  field.Time
	LastLockoutAt field.Time
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (l loginAttemptModel) Table(newTableName string) *loginAttemptModel {
	l.loginAttemptModelDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l loginAttemptModel) As(alias string) *loginAttemptModel {
	l.loginAttemptModelDo.DO = *(l.loginAttemptModelDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *loginAttemptModel) updateTableName(table string) *loginAttemptModel {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewField(table, "id")
	l.AttemptKey = field.NewString(table, "attempt_key")
	l.UserID = field.NewField(table, "user_id")
	l.FailedCount = field.NewInt(table, "failed_count")
	l.LockoutCount = field.NewInt(table, "lockout_count")
	l.LockedUntil = field.NewTime(table, "locked_until")
	l.LastFailedAt = field.NewTime(table, "last_failed_at")
	l.LastLockoutAt = field.NewTime(table, "last_lockout_at")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *loginAttemptModel) WithContext(ctx context.Context) *loginAttemptModelDo {
	return l.loginAttemptModelDo.WithContext(ctx)
}

func (l loginAttemptModel) TableName() string { return l.loginAttemptModelDo.TableName() }

func (l loginAttemptModel) Alias() string { return l.loginAttemptModelDo.Alias() }

func (l loginAttemptModel) Columns(cols ...field.Expr) gen.Columns {
	return l.loginAttemptModelDo.Columns(cols...)
}

func (l *loginAttemptModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *loginAttemptModel) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 10)
	l.fieldMap["id"] = l.ID
	l.fieldMap["attempt_key"] = l.AttemptKey
	l.fieldMap["user_id"] = l.UserID
	l.fieldMap["failed_count"] = l.FailedCount
	l.fieldMap["lockout_count"] = l.LockoutCount
	l.fieldMap["locked_until"] = l.LockedUntil
	l.fieldMap["last_failed_at"] = l.LastFailedAt
	l.fieldMap["last_lockout_at"] = l.LastLockoutAt
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l loginAttemptModel) clone(db *gorm.DB) loginAttemptModel {
	l.loginAttemptModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l loginAttemptModel) replaceDB(db *gorm.DB) loginAttemptModel {
	l.loginAttemptModelDo.ReplaceDB(db)
	return l
}

type loginAttemptModelDo struct{ gen.DO }

func (l loginAttemptModelDo) Debug() *loginAttemptModelDo {
	return l.withDO(l.DO.Debug())
}

func (l loginAttemptModelDo) WithContext(ctx context.Context) *loginAttemptModelDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l loginAttemptModelDo) ReadDB() *loginAttemptModelDo {
	return l.Clauses(dbresolver.Read)
}

func (l loginAttemptModelDo) WriteDB() *loginAttemptModelDo {
	return l.Clauses(dbresolver.Write)
}

func (l loginAttemptModelDo) Session(config *gorm.Session) *loginAttemptModelDo {
	return l.withDO(l.DO.Session(config))
}

func (l loginAttemptModelDo) Clauses(conds ...clause.Expression) *loginAttemptModelDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l loginAttemptModelDo) Returning(value interface{}, columns ...string) *loginAttemptModelDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l loginAttemptModelDo) Not(conds ...gen.Condition) *loginAttemptModelDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l loginAttemptModelDo) Or(conds ...gen.Condition) *loginAttemptModelDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l loginAttemptModelDo) Select(conds ...field.Expr) *loginAttemptModelDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l loginAttemptModelDo) Where(conds ...gen.Condition) *loginAttemptModelDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l loginAttemptModelDo) Order(conds ...field.Expr) *loginAttemptModelDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l loginAttemptModelDo) Distinct(cols ...field.Expr) *loginAttemptModelDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l loginAttemptModelDo) Omit(cols ...field.Expr) *loginAttemptModelDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l loginAttemptModelDo) Join(table schema.Tabler, on ...field.Expr) *loginAttemptModelDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l loginAttemptModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *loginAttemptModelDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l loginAttemptModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *loginAttemptModelDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l loginAttemptModelDo) Group(cols ...field.Expr) *loginAttemptModelDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l loginAttemptModelDo) Having(conds ...gen.Condition) *loginAttemptModelDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l loginAttemptModelDo) Limit(limit int) *loginAttemptModelDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l loginAttemptModelDo) Offset(offset int) *loginAttemptModelDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l loginAttemptModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *loginAttemptModelDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l loginAttemptModelDo) Unscoped() *loginAttemptModelDo {
	return l.withDO(l.DO.Unscoped())
}

func (l loginAttemptModelDo) Create(values ...*model.LoginAttemptModel) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l loginAttemptModelDo) CreateInBatches(values []*model.LoginAttemptModel, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l loginAttemptModelDo) Save(values ...*model.LoginAttemptModel) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l loginAttemptModelDo) First() (*model.LoginAttemptModel, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAttemptModel), nil
	}
}

func (l loginAttemptModelDo) Take() (*model.LoginAttemptModel, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAttemptModel), nil
	}
}

func (l loginAttemptModelDo) Last() (*model.LoginAttemptModel, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAttemptModel), nil
	}
}

func (l loginAttemptModelDo) Find() ([]*model.LoginAttemptModel, error) {
	result, err := l.DO.Find()
	return result.([]*model.LoginAttemptModel), err
}

func (l loginAttemptModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LoginAttemptModel, err error) {
	buf := make([]*model.LoginAttemptModel, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l loginAttemptModelDo) FindInBatches(result *[]*model.LoginAttemptModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l loginAttemptModelDo) Attrs(attrs ...field.AssignExpr) *loginAttemptModelDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l loginAttemptModelDo) Assign(attrs ...field.AssignExpr) *loginAttemptModelDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l loginAttemptModelDo) Joins(fields ...field.RelationField) *loginAttemptModelDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l loginAttemptModelDo) Preload(fields ...field.RelationField) *loginAttemptModelDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l loginAttemptModelDo) FirstOrInit() (*model.LoginAttemptModel, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAttemptModel), nil
	}
}

func (l loginAttemptModelDo) FirstOrCreate() (*model.LoginAttemptModel, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAttemptModel), nil
	}
}

func (l loginAttemptModelDo) FindByPage(offset int, limit int) (result []*model.LoginAttemptModel, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l loginAttemptModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l loginAttemptModelDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l loginAttemptModelDo) Delete(models ...*model.LoginAttemptModel) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *loginAttemptModelDo) withDO(do gen.Dao) *loginAttemptModelDo {
	l.DO = *do.(*gen.DO)
	return l
}
