// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newMenuItemModel(db *gorm.DB, opts ...gen.DOOption) menuItemModel {
	_menuItemModel := menuItemModel{}

	_menuItemModel.menuItemModelDo.UseDB(db, opts...)
	_menuItemModel.menuItemModelDo.UseModel(&model.MenuItemModel{})

	tableName := _menuItemModel.menuItemModelDo.TableName()
	_menuItemModel.ALL = field.NewAsterisk(tableName)
	_menuItemModel.ID = field.NewField(tableName, "id")
	_menuItemModel.MerchantID = field.NewField(tableName, "merchant_id")
	_menuItemModel.Name = field.NewString(tableName, "name")
	_menuItemModel.Description = field.NewString(tableName, "description")
	_menuItemModel.Category = field.NewString(tableName, "category")
	_menuItemModel.Price = field.NewInt(tableName, "price")
	_menuItemModel.Currency = field.NewString(tableName, "currency")
	_menuItemModel.PrepMinutes = field.NewInt(tableName, "prep_minutes")
	_menuItemModel.IsAvailable = field.NewBool(tableName, "is_available")
	_menuItemModel.IsPopular = field.NewBool(tableName, "is_popular")
	_menuItemModel.DisplayOrder = field.NewInt(tableName, "display_order")
	_menuItemModel.ImageURL = field.NewString(tableName, "image_url")
	_menuItemModel.ExternalURL = field.NewString(tableName, "external_url")
	_menuItemModel.CreatedAt = field.NewTime(tableName, "created_at")
	_menuItemModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_menuItemModel.DeletedAt = field.NewField(tableName, "deleted_at")

	_menuItemModel.fillFieldMap()

	return _menuItemModel
}

type menuItemModel struct {
	menuItemModelDo menuItemModelDo

	ALL          field.Asterisk
	ID           field.Field
	MerchantID   field.Field
	Name         field.String
	Description  field.String
	Category     field.String
	Price        field.Int
	Currency     field.String
	PrepMinutes  field.Int
	IsAvailable  field.Bool
	IsPopular    field.Bool
	DisplayOrder field.Int
	ImageURL     field.String
	ExternalURL  field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field

	fieldMap map[string]field.Expr
}

func (m menuItemModel) Table(newTableName string) *menuItemModel {
	m.menuItemModelDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m menuItemModel) As(alias string) *menuItemModel {
	m.menuItemModelDo.DO = *(m.menuItemModelDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *menuItemModel) updateTableName(table string) *menuItemModel {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewField(table, "id")
	m.MerchantID = field.NewField(table, "merchant_id")
	m.Name = field.NewString(table, "name")
	m.Description = field.NewString(table, "description")
	m.Category = field.NewString(table, "category")
	m.Price = field.NewInt(table, "price")
	m.Currency = field.NewString(table, "currency")
	m.PrepMinutes = field.NewInt(table, "prep_minutes")
	m.IsAvailable = field.NewBool(table, "is_available")
	m.IsPopular = field.NewBool(table, "is_popular")
	m.DisplayOrder = field.NewInt(table, "display_order")
	m.ImageURL = field.NewString(table, "image_url")
	m.ExternalURL = field.NewString(table, "external_url")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *menuItemModel) WithContext(ctx context.Context) *menuItemModelDo {
	return m.menuItemModelDo.WithContext(ctx)
}

func (m menuItemModel) TableName() string { return m.menuItemModelDo.TableName() }

func (m menuItemModel) Alias() string { return m.menuItemModelDo.Alias() }

func (m menuItemModel) Columns(cols ...field.Expr) gen.Columns {
	return m.menuItemModelDo.Columns(cols...)
}

func (m *menuItemModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *menuItemModel) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 16)
	m.fieldMap["id"] = m.ID
	m.fieldMap["merchant_id"] = m.MerchantID
	m.fieldMap["name"] = m.Name
	m.fieldMap["description"] = m.Description
	m.fieldMap["category"] = m.Category
	m.fieldMap["price"] = m.Price
	m.fieldMap["currency"] = m.Currency
	m.fieldMap["prep_minutes"] = m.PrepMinutes
	m.fieldMap["is_available"] = m.IsAvailable
	m.fieldMap["is_popular"] = m.IsPopular
	m.fieldMap["display_order"] = m.DisplayOrder
	m.fieldMap["image_url"] = m.ImageURL
	m.fieldMap["external_url"] = m.ExternalURL
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
}

func (m menuItemModel) clone(db *gorm.DB) menuItemModel {
	m.menuItemModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m menuItemModel) replaceDB(db *gorm.DB) menuItemModel {
	m.menuItemModelDo.ReplaceDB(db)
	return m
}

type menuItemModelDo struct{ gen.DO }

func (m menuItemModelDo) Debug() *menuItemModelDo {
	return m.withDO(m.DO.Debug())
}

func (m menuItemModelDo) WithContext(ctx context.Context) *menuItemModelDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m menuItemModelDo) ReadDB() *menuItemModelDo {
	return m.Clauses(dbresolver.Read)
}

func (m menuItemModelDo) WriteDB() *menuItemModelDo {
	return m.Clauses(dbresolver.Write)
}

func (m menuItemModelDo) Session(config *gorm.Session) *menuItemModelDo {
	return m.withDO(m.DO.Session(config))
}

func (m menuItemModelDo) Clauses(conds ...clause.Expression) *menuItemModelDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m menuItemModelDo) Returning(value interface{}, columns ...string) *menuItemModelDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m menuItemModelDo) Not(conds ...gen.Condition) *menuItemModelDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m menuItemModelDo) Or(conds ...gen.Condition) *menuItemModelDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m menuItemModelDo) Select(conds ...field.Expr) *menuItemModelDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m menuItemModelDo) Where(conds ...gen.Condition) *menuItemModelDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m menuItemModelDo) Order(conds ...field.Expr) *menuItemModelDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m menuItemModelDo) Distinct(cols ...field.Expr) *menuItemModelDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m menuItemModelDo) Omit(cols ...field.Expr) *menuItemModelDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m menuItemModelDo) Join(table schema.Tabler, on ...field.Expr) *menuItemModelDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m menuItemModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *menuItemModelDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m menuItemModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *menuItemModelDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m menuItemModelDo) Group(cols ...field.Expr) *menuItemModelDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m menuItemModelDo) Having(conds ...gen.Condition) *menuItemModelDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m menuItemModelDo) Limit(limit int) *menuItemModelDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m menuItemModelDo) Offset(offset int) *menuItemModelDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m menuItemModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *menuItemModelDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m menuItemModelDo) Unscoped() *menuItemModelDo {
	return m.withDO(m.DO.Unscoped())
}

func (m menuItemModelDo) Create(values ...*model.MenuItemModel) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m menuItemModelDo) CreateInBatches(values []*model.MenuItemModel, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m menuItemModelDo) Save(values ...*model.MenuItemModel) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m menuItemModelDo) First() (*model.MenuItemModel, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuItemModel), nil
	}
}

func (m menuItemModelDo) Take() (*model.MenuItemModel, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuItemModel), nil
	}
}

func (m menuItemModelDo) Last() (*model.MenuItemModel, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuItemModel), nil
	}
}

func (m menuItemModelDo) Find() ([]*model.MenuItemModel, error) {
	result, err := m.DO.Find()
	return result.([]*model.MenuItemModel), err
}

func (m menuItemModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenuItemModel, err error) {
	buf := make([]*model.MenuItemModel, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m menuItemModelDo) FindInBatches(result *[]*model.MenuItemModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m menuItemModelDo) Attrs(attrs ...field.AssignExpr) *menuItemModelDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m menuItemModelDo) Assign(attrs ...field.AssignExpr) *menuItemModelDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m menuItemModelDo) Joins(fields ...field.RelationField) *menuItemModelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m menuItemModelDo) Preload(fields ...field.RelationField) *menuItemModelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m menuItemModelDo) FirstOrInit() (*model.MenuItemModel, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuItemModel), nil
	}
}

func (m menuItemModelDo) FirstOrCreate() (*model.MenuItemModel, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuItemModel), nil
	}
}

func (m menuItemModelDo) FindByPage(offset int, limit int) (result []*model.MenuItemModel, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m menuItemModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m menuItemModelDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m menuItemModelDo) Delete(models ...*model.MenuItemModel) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *menuItemModelDo) withDO(do gen.Dao) *menuItemModelDo {
	m.DO = *do.(*gen.DO)
	return m
}
