// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newMerchantLocationNotificationModel(db *gorm.DB, opts ...gen.DOOption) merchantLocationNotificationModel {
	_merchantLocationNotificationModel := merchantLocationNotificationModel{}

	_merchantLocationNotificationModel.merchantLocationNotificationModelDo.UseDB(db, opts...)
	_merchantLocationNotificationModel.merchantLocationNotificationModelDo.UseModel(&model.MerchantLocationNotificationModel{})

	tableName := _merchantLocationNotificationModel.merchantLocationNotificationModelDo.TableName()
	_merchantLocationNotificationModel.ALL = field.NewAsterisk(tableName)
	_merchantLocationNotificationModel.ID = field.NewField(tableName, "id")
	_merchantLocationNotificationModel.MerchantID = field.NewField(tableName, "merchant_id")
	_merchantLocationNotificationModel.AddressID = field.NewField(tableName, "address_id")
	_merchantLocationNotificationModel.LocationName = field.NewString(tableName, "location_name")
	_merchantLocationNotificationModel.FullAddress = field.NewString(tableName, "full_address")
	_merchantLocationNotificationModel.Latitude = field.NewFloat64(tableName, "latitude")
	_merchantLocationNotificationModel.Longitude = field.NewFloat64(tableName, "longitude")
	_merchantLocationNotificationModel.HintMessage = field.NewString(tableName, "hint_message")
	_merchantLocationNotificationModel.TotalSent = field.NewInt(tableName, "total_sent")
	_merchantLocationNotificationModel.TotalFailed = field.NewInt(tableName, "total_failed")
	_merchantLocationNotificationModel.PublishedAt = field.NewTime(tableName, "published_at")
	_merchantLocationNotificationModel.CreatedAt = field.NewTime(tableName, "created_at")
	_merchantLocationNotificationModel.UpdatedAt = field.NewTime(tableName, "updated_at")

	_merchantLocationNotificationModel.fillFieldMap()

	return _merchantLocationNotificationModel
}

type merchantLocationNotificationModel struct {
	merchantLocationNotificationModelDo merchantLocationNotificationModelDo

	ALL          field.Asterisk
	ID           field.Field
	MerchantID   field.Field
	AddressID    field.Field
	LocationName field.String
	FullAddress  field.String
	Latitude     field.Float64
	Longitude    field.Float64
	HintMessage  field.String
	TotalSent    field.Int
	TotalFailed  field.Int
	PublishedAt  field.Time
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (m merchantLocationNotificationModel) Table(newTableName string) *merchantLocationNotificationModel {
	m.merchantLocationNotificationModelDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m merchantLocationNotificationModel) As(alias string) *merchantLocationNotificationModel {
	m.merchantLocationNotificationModelDo.DO = *(m.merchantLocationNotificationModelDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *merchantLocationNotificationModel) updateTableName(table string) *merchantLocationNotificationModel {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewField(table, "id")
	m.MerchantID = field.NewField(table, "merchant_id")
	m.AddressID = field.NewField(table, "address_id")
	m.LocationName = field.NewString(table, "location_name")
	m.FullAddress = field.NewString(table, "full_address")
	m.Latitude = field.NewFloat64(table, "latitude")
	m.Longitude = field.NewFloat64(table, "longitude")
	m.HintMessage = field.NewString(table, "hint_message")
	m.TotalSent = field.NewInt(table, "total_sent")
	m.TotalFailed = field.NewInt(table, "total_failed")
	m.PublishedAt = field.NewTime(table, "published_at")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *merchantLocationNotificationModel) WithContext(ctx context.Context) *merchantLocationNotificationModelDo {
	return m.merchantLocationNotificationModelDo.WithContext(ctx)
}

func (m merchantLocationNotificationModel) TableName() string {
	return m.merchantLocationNotificationModelDo.TableName()
}

func (m merchantLocationNotificationModel) Alias() string {
	return m.merchantLocationNotificationModelDo.Alias()
}

func (m merchantLocationNotificationModel) Columns(cols ...field.Expr) gen.Columns {
	return m.merchantLocationNotificationModelDo.Columns(cols...)
}

func (m *merchantLocationNotificationModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *merchantLocationNotificationModel) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 13)
	m.fieldMap["id"] = m.ID
	m.fieldMap["merchant_id"] = m.MerchantID
	m.fieldMap["address_id"] = m.AddressID
	m.fieldMap["location_name"] = m.LocationName
	m.fieldMap["full_address"] = m.FullAddress
	m.fieldMap["latitude"] = m.Latitude
	m.fieldMap["longitude"] = m.Longitude
	m.fieldMap["hint_message"] = m.HintMessage
	m.fieldMap["total_sent"] = m.TotalSent
	m.fieldMap["total_failed"] = m.TotalFailed
	m.fieldMap["published_at"] = m.PublishedAt
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m merchantLocationNotificationModel) clone(db *gorm.DB) merchantLocationNotificationModel {
	m.merchantLocationNotificationModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m merchantLocationNotificationModel) replaceDB(db *gorm.DB) merchantLocationNotificationModel {
	m.merchantLocationNotificationModelDo.ReplaceDB(db)
	return m
}

type merchantLocationNotificationModelDo struct{ gen.DO }

func (m merchantLocationNotificationModelDo) Debug() *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Debug())
}

func (m merchantLocationNotificationModelDo) WithContext(ctx context.Context) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m merchantLocationNotificationModelDo) ReadDB() *merchantLocationNotificationModelDo {
	return m.Clauses(dbresolver.Read)
}

func (m merchantLocationNotificationModelDo) WriteDB() *merchantLocationNotificationModelDo {
	return m.Clauses(dbresolver.Write)
}

func (m merchantLocationNotificationModelDo) Session(config *gorm.Session) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Session(config))
}

func (m merchantLocationNotificationModelDo) Clauses(conds ...clause.Expression) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m merchantLocationNotificationModelDo) Returning(value interface{}, columns ...string) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m merchantLocationNotificationModelDo) Not(conds ...gen.Condition) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m merchantLocationNotificationModelDo) Or(conds ...gen.Condition) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m merchantLocationNotificationModelDo) Select(conds ...field.Expr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m merchantLocationNotificationModelDo) Where(conds ...gen.Condition) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m merchantLocationNotificationModelDo) Order(conds ...field.Expr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m merchantLocationNotificationModelDo) Distinct(cols ...field.Expr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m merchantLocationNotificationModelDo) Omit(cols ...field.Expr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m merchantLocationNotificationModelDo) Join(table schema.Tabler, on ...field.Expr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m merchantLocationNotificationModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m merchantLocationNotificationModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m merchantLocationNotificationModelDo) Group(cols ...field.Expr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m merchantLocationNotificationModelDo) Having(conds ...gen.Condition) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m merchantLocationNotificationModelDo) Limit(limit int) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m merchantLocationNotificationModelDo) Offset(offset int) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m merchantLocationNotificationModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m merchantLocationNotificationModelDo) Unscoped() *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Unscoped())
}

func (m merchantLocationNotificationModelDo) Create(values ...*model.MerchantLocationNotificationModel) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m merchantLocationNotificationModelDo) CreateInBatches(values []*model.MerchantLocationNotificationModel, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m merchantLocationNotificationModelDo) Save(values ...*model.MerchantLocationNotificationModel) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m merchantLocationNotificationModelDo) First() (*model.MerchantLocationNotificationModel, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantLocationNotificationModel), nil
	}
}

func (m merchantLocationNotificationModelDo) Take() (*model.MerchantLocationNotificationModel, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantLocationNotificationModel), nil
	}
}

func (m merchantLocationNotificationModelDo) Last() (*model.MerchantLocationNotificationModel, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantLocationNotificationModel), nil
	}
}

func (m merchantLocationNotificationModelDo) Find() ([]*model.MerchantLocationNotificationModel, error) {
	result, err := m.DO.Find()
	return result.([]*model.MerchantLocationNotificationModel), err
}

func (m merchantLocationNotificationModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerchantLocationNotificationModel, err error) {
	buf := make([]*model.MerchantLocationNotificationModel, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m merchantLocationNotificationModelDo) FindInBatches(result *[]*model.MerchantLocationNotificationModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m merchantLocationNotificationModelDo) Attrs(attrs ...field.AssignExpr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m merchantLocationNotificationModelDo) Assign(attrs ...field.AssignExpr) *merchantLocationNotificationModelDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m merchantLocationNotificationModelDo) Joins(fields ...field.RelationField) *merchantLocationNotificationModelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m merchantLocationNotificationModelDo) Preload(fields ...field.RelationField) *merchantLocationNotificationModelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m merchantLocationNotificationModelDo) FirstOrInit() (*model.MerchantLocationNotificationModel, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantLocationNotificationModel), nil
	}
}

func (m merchantLocationNotificationModelDo) FirstOrCreate() (*model.MerchantLocationNotificationModel, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantLocationNotificationModel), nil
	}
}

func (m merchantLocationNotificationModelDo) FindByPage(offset int, limit int) (result []*model.MerchantLocationNotificationModel, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m merchantLocationNotificationModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m merchantLocationNotificationModelDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m merchantLocationNotificationModelDo) Delete(models ...*model.MerchantLocationNotificationModel) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *merchantLocationNotificationModelDo) withDO(do gen.Dao) *merchantLocationNotificationModelDo {
	m.DO = *do.(*gen.DO)
	return m
}
