// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newNotificationLogModel(db *gorm.DB, opts ...gen.DOOption) notificationLogModel {
	_notificationLogModel := notificationLogModel{}

	_notificationLogModel.notificationLogModelDo.UseDB(db, opts...)
	_notificationLogModel.notificationLogModelDo.UseModel(&model.NotificationLogModel{})

	tableName := _notificationLogModel.notificationLogModelDo.TableName()
	_notificationLogModel.ALL = field.NewAsterisk(tableName)
	_notificationLogModel.ID = field.NewField(tableName, "id")
	_notificationLogModel.NotificationID = field.NewField(tableName, "notification_id")
	_notificationLogModel.UserID = field.NewField(tableName, "user_id")
	_notificationLogModel.DeviceID = field.NewField(tableName, "device_id")
	_notificationLogModel.Status = field.NewString(tableName, "status")
	_notificationLogModel.FCMMessageID = field.NewString(tableName, "fcm_message_id")
	_notificationLogModel.ErrorMessage = field.NewString(tableName, "error_message")
	_notificationLogModel.SentAt = field.NewTime(tableName, "sent_at")

	_notificationLogModel.fillFieldMap()

	return _notificationLogModel
}

type notificationLogModel struct {
	notificationLogModelDo notificationLogModelDo

	ALL            field.Asterisk
	ID             field.Field
	NotificationID field.Field
	UserID         field.Field
	DeviceID       field.Field
	Status         field.String
	FCMMessageID   field.String
	ErrorMessage   field.String
	SentAt         field.Time

	fieldMap map[string]field.Expr
}

func (n notificationLogModel) Table(newTableName string) *notificationLogModel {
	n.notificationLogModelDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notificationLogModel) As(alias string) *notificationLogModel {
	n.notificationLogModelDo.DO = *(n.notificationLogModelDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notificationLogModel) updateTableName(table string) *notificationLogModel {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewField(table, "id")
	n.NotificationID = field.NewField(table, "notification_id")
	n.UserID = field.NewField(table, "user_id")
	n.DeviceID = field.NewField(table, "device_id")
	n.Status = field.NewString(table, "status")
	n.FCMMessageID = field.NewString(table, "fcm_message_id")
	n.ErrorMessage = field.NewString(table, "error_message")
	n.SentAt = field.NewTime(table, "sent_at")

	n.fillFieldMap()

	return n
}

func (n *notificationLogModel) WithContext(ctx context.Context) *notificationLogModelDo {
	return n.notificationLogModelDo.WithContext(ctx)
}

func (n notificationLogModel) TableName() string { return n.notificationLogModelDo.TableName() }

func (n notificationLogModel) Alias() string { return n.notificationLogModelDo.Alias() }

func (n notificationLogModel) Columns(cols ...field.Expr) gen.Columns {
	return n.notificationLogModelDo.Columns(cols...)
}

func (n *notificationLogModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notificationLogModel) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 8)
	n.fieldMap["id"] = n.ID
	n.fieldMap["notification_id"] = n.NotificationID
	n.fieldMap["user_id"] = n.UserID
	n.fieldMap["device_id"] = n.DeviceID
	n.fieldMap["status"] = n.Status
	n.fieldMap["fcm_message_id"] = n.FCMMessageID
	n.fieldMap["error_message"] = n.ErrorMessage
	n.fieldMap["sent_at"] = n.SentAt
}

func (n notificationLogModel) clone(db *gorm.DB) notificationLogModel {
	n.notificationLogModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notificationLogModel) replaceDB(db *gorm.DB) notificationLogModel {
	n.notificationLogModelDo.ReplaceDB(db)
	return n
}

type notificationLogModelDo struct{ gen.DO }

func (n notificationLogModelDo) Debug() *notificationLogModelDo {
	return n.withDO(n.DO.Debug())
}

func (n notificationLogModelDo) WithContext(ctx context.Context) *notificationLogModelDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notificationLogModelDo) ReadDB() *notificationLogModelDo {
	return n.Clauses(dbresolver.Read)
}

func (n notificationLogModelDo) WriteDB() *notificationLogModelDo {
	return n.Clauses(dbresolver.Write)
}

func (n notificationLogModelDo) Session(config *gorm.Session) *notificationLogModelDo {
	return n.withDO(n.DO.Session(config))
}

func (n notificationLogModelDo) Clauses(conds ...clause.Expression) *notificationLogModelDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notificationLogModelDo) Returning(value interface{}, columns ...string) *notificationLogModelDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notificationLogModelDo) Not(conds ...gen.Condition) *notificationLogModelDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notificationLogModelDo) Or(conds ...gen.Condition) *notificationLogModelDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notificationLogModelDo) Select(conds ...field.Expr) *notificationLogModelDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notificationLogModelDo) Where(conds ...gen.Condition) *notificationLogModelDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notificationLogModelDo) Order(conds ...field.Expr) *notificationLogModelDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notificationLogModelDo) Distinct(cols ...field.Expr) *notificationLogModelDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notificationLogModelDo) Omit(cols ...field.Expr) *notificationLogModelDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notificationLogModelDo) Join(table schema.Tabler, on ...field.Expr) *notificationLogModelDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notificationLogModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *notificationLogModelDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notificationLogModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *notificationLogModelDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notificationLogModelDo) Group(cols ...field.Expr) *notificationLogModelDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notificationLogModelDo) Having(conds ...gen.Condition) *notificationLogModelDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notificationLogModelDo) Limit(limit int) *notificationLogModelDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notificationLogModelDo) Offset(offset int) *notificationLogModelDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notificationLogModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *notificationLogModelDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notificationLogModelDo) Unscoped() *notificationLogModelDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notificationLogModelDo) Create(values ...*model.NotificationLogModel) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notificationLogModelDo) CreateInBatches(values []*model.NotificationLogModel, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notificationLogModelDo) Save(values ...*model.NotificationLogModel) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notificationLogModelDo) First() (*model.NotificationLogModel, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationLogModel), nil
	}
}

func (n notificationLogModelDo) Take() (*model.NotificationLogModel, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationLogModel), nil
	}
}

func (n notificationLogModelDo) Last() (*model.NotificationLogModel, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationLogModel), nil
	}
}

func (n notificationLogModelDo) Find() ([]*model.NotificationLogModel, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotificationLogModel), err
}

func (n notificationLogModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationLogModel, err error) {
	buf := make([]*model.NotificationLogModel, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notificationLogModelDo) FindInBatches(result *[]*model.NotificationLogModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notificationLogModelDo) Attrs(attrs ...field.AssignExpr) *notificationLogModelDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notificationLogModelDo) Assign(attrs ...field.AssignExpr) *notificationLogModelDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notificationLogModelDo) Joins(fields ...field.RelationField) *notificationLogModelDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notificationLogModelDo) Preload(fields ...field.RelationField) *notificationLogModelDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notificationLogModelDo) FirstOrInit() (*model.NotificationLogModel, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationLogModel), nil
	}
}

func (n notificationLogModelDo) FirstOrCreate() (*model.NotificationLogModel, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationLogModel), nil
	}
}

func (n notificationLogModelDo) FindByPage(offset int, limit int) (result []*model.NotificationLogModel, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notificationLogModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notificationLogModelDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notificationLogModelDo) Delete(models ...*model.NotificationLogModel) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notificationLogModelDo) withDO(do gen.Dao) *notificationLogModelDo {
	n.DO = *do.(*gen.DO)
	return n
}
