// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newUserDeviceModel(db *gorm.DB, opts ...gen.DOOption) userDeviceModel {
	_userDeviceModel := userDeviceModel{}

	_userDeviceModel.userDeviceModelDo.UseDB(db, opts...)
	_userDeviceModel.userDeviceModelDo.UseModel(&model.UserDeviceModel{})

	tableName := _userDeviceModel.userDeviceModelDo.TableName()
	_userDeviceModel.ALL = field.NewAsterisk(tableName)
	_userDeviceModel.ID = field.NewField(tableName, "id")
	_userDeviceModel.UserID = field.NewField(tableName, "user_id")
	_userDeviceModel.FCMToken = field.NewString(tableName, "fcm_token")
	_userDeviceModel.DeviceID = field.NewString(tableName, "device_id")
	_userDeviceModel.Platform = field.NewString(tableName, "platform")
	_userDeviceModel.IsActive = field.NewBool(tableName, "is_active")
	_userDeviceModel.CreatedAt = field.NewTime(tableName, "created_at")
	_userDeviceModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userDeviceModel.DeletedAt = field.NewField(tableName, "deleted_at")

	_userDeviceModel.fillFieldMap()

	return _userDeviceModel
}

type userDeviceModel struct {
	userDeviceModelDo userDeviceModelDo

	ALL       field.Asterisk
	ID        field.Field
	UserID    field.Field
	FCMToken  field.String
	DeviceID  field.String
	Platform  field.String
	IsActive  field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (u userDeviceModel) Table(newTableName string) *userDeviceModel {
	u.userDeviceModelDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userDeviceModel) As(alias string) *userDeviceModel {
	u.userDeviceModelDo.DO = *(u.userDeviceModelDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userDeviceModel) updateTableName(table string) *userDeviceModel {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.UserID = field.NewField(table, "user_id")
	u.FCMToken = field.NewString(table, "fcm_token")
	u.DeviceID = field.NewString(table, "device_id")
	u.Platform = field.NewString(table, "platform")
	u.IsActive = field.NewBool(table, "is_active")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *userDeviceModel) WithContext(ctx context.Context) *userDeviceModelDo {
	return u.userDeviceModelDo.WithContext(ctx)
}

func (u userDeviceModel) TableName() string { return u.userDeviceModelDo.TableName() }

func (u userDeviceModel) Alias() string { return u.userDeviceModelDo.Alias() }

func (u userDeviceModel) Columns(cols ...field.Expr) gen.Columns {
	return u.userDeviceModelDo.Columns(cols...)
}

func (u *userDeviceModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userDeviceModel) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 9)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["fcm_token"] = u.FCMToken
	u.fieldMap["device_id"] = u.DeviceID
	u.fieldMap["platform"] = u.Platform
	u.fieldMap["is_active"] = u.IsActive
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u userDeviceModel) clone(db *gorm.DB) userDeviceModel {
	u.userDeviceModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userDeviceModel) replaceDB(db *gorm.DB) userDeviceModel {
	u.userDeviceModelDo.ReplaceDB(db)
	return u
}

type userDeviceModelDo struct{ gen.DO }

func (u userDeviceModelDo) Debug() *userDeviceModelDo {
	return u.withDO(u.DO.Debug())
}

func (u userDeviceModelDo) WithContext(ctx context.Context) *userDeviceModelDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDeviceModelDo) ReadDB() *userDeviceModelDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDeviceModelDo) WriteDB() *userDeviceModelDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDeviceModelDo) Session(config *gorm.Session) *userDeviceModelDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDeviceModelDo) Clauses(conds ...clause.Expression) *userDeviceModelDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDeviceModelDo) Returning(value interface{}, columns ...string) *userDeviceModelDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDeviceModelDo) Not(conds ...gen.Condition) *userDeviceModelDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDeviceModelDo) Or(conds ...gen.Condition) *userDeviceModelDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDeviceModelDo) Select(conds ...field.Expr) *userDeviceModelDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDeviceModelDo) Where(conds ...gen.Condition) *userDeviceModelDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDeviceModelDo) Order(conds ...field.Expr) *userDeviceModelDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDeviceModelDo) Distinct(cols ...field.Expr) *userDeviceModelDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDeviceModelDo) Omit(cols ...field.Expr) *userDeviceModelDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDeviceModelDo) Join(table schema.Tabler, on ...field.Expr) *userDeviceModelDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDeviceModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userDeviceModelDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDeviceModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *userDeviceModelDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDeviceModelDo) Group(cols ...field.Expr) *userDeviceModelDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDeviceModelDo) Having(conds ...gen.Condition) *userDeviceModelDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDeviceModelDo) Limit(limit int) *userDeviceModelDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDeviceModelDo) Offset(offset int) *userDeviceModelDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDeviceModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userDeviceModelDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDeviceModelDo) Unscoped() *userDeviceModelDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDeviceModelDo) Create(values ...*model.UserDeviceModel) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDeviceModelDo) CreateInBatches(values []*model.UserDeviceModel, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDeviceModelDo) Save(values ...*model.UserDeviceModel) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDeviceModelDo) First() (*model.UserDeviceModel, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDeviceModel), nil
	}
}

func (u userDeviceModelDo) Take() (*model.UserDeviceModel, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDeviceModel), nil
	}
}

func (u userDeviceModelDo) Last() (*model.UserDeviceModel, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDeviceModel), nil
	}
}

func (u userDeviceModelDo) Find() ([]*model.UserDeviceModel, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserDeviceModel), err
}

func (u userDeviceModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserDeviceModel, err error) {
	buf := make([]*model.UserDeviceModel, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDeviceModelDo) FindInBatches(result *[]*model.UserDeviceModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDeviceModelDo) Attrs(attrs ...field.AssignExpr) *userDeviceModelDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDeviceModelDo) Assign(attrs ...field.AssignExpr) *userDeviceModelDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDeviceModelDo) Joins(fields ...field.RelationField) *userDeviceModelDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDeviceModelDo) Preload(fields ...field.RelationField) *userDeviceModelDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDeviceModelDo) FirstOrInit() (*model.UserDeviceModel, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDeviceModel), nil
	}
}

func (u userDeviceModelDo) FirstOrCreate() (*model.UserDeviceModel, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDeviceModel), nil
	}
}

func (u userDeviceModelDo) FindByPage(offset int, limit int) (result []*model.UserDeviceModel, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDeviceModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDeviceModelDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDeviceModelDo) Delete(models ...*model.UserDeviceModel) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDeviceModelDo) withDO(do gen.Dao) *userDeviceModelDo {
	u.DO = *do.(*gen.DO)
	return u
}
