// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"radar/internal/infra/persistence/model"
)

func newUserMerchantSubscriptionModel(db *gorm.DB, opts ...gen.DOOption) userMerchantSubscriptionModel {
	_userMerchantSubscriptionModel := userMerchantSubscriptionModel{}

	_userMerchantSubscriptionModel.userMerchantSubscriptionModelDo.UseDB(db, opts...)
	_userMerchantSubscriptionModel.userMerchantSubscriptionModelDo.UseModel(&model.UserMerchantSubscriptionModel{})

	tableName := _userMerchantSubscriptionModel.userMerchantSubscriptionModelDo.TableName()
	_userMerchantSubscriptionModel.ALL = field.NewAsterisk(tableName)
	_userMerchantSubscriptionModel.ID = field.NewField(tableName, "id")
	_userMerchantSubscriptionModel.UserID = field.NewField(tableName, "user_id")
	_userMerchantSubscriptionModel.MerchantID = field.NewField(tableName, "merchant_id")
	_userMerchantSubscriptionModel.IsActive = field.NewBool(tableName, "is_active")
	_userMerchantSubscriptionModel.NotificationRadius = field.NewFloat64(tableName, "notification_radius")
	_userMerchantSubscriptionModel.SubscribedAt = field.NewTime(tableName, "subscribed_at")
	_userMerchantSubscriptionModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userMerchantSubscriptionModel.DeletedAt = field.NewField(tableName, "deleted_at")

	_userMerchantSubscriptionModel.fillFieldMap()

	return _userMerchantSubscriptionModel
}

type userMerchantSubscriptionModel struct {
	userMerchantSubscriptionModelDo userMerchantSubscriptionModelDo

	ALL                field.Asterisk
	ID                 field.Field
	UserID             field.Field
	MerchantID         field.Field
	IsActive           field.Bool
	NotificationRadius field.Float64
	SubscribedAt       field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field

	fieldMap map[string]field.Expr
}

func (u userMerchantSubscriptionModel) Table(newTableName string) *userMerchantSubscriptionModel {
	u.userMerchantSubscriptionModelDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userMerchantSubscriptionModel) As(alias string) *userMerchantSubscriptionModel {
	u.userMerchantSubscriptionModelDo.DO = *(u.userMerchantSubscriptionModelDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userMerchantSubscriptionModel) updateTableName(table string) *userMerchantSubscriptionModel {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.UserID = field.NewField(table, "user_id")
	u.MerchantID = field.NewField(table, "merchant_id")
	u.IsActive = field.NewBool(table, "is_active")
	u.NotificationRadius = field.NewFloat64(table, "notification_radius")
	u.SubscribedAt = field.NewTime(table, "subscribed_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *userMerchantSubscriptionModel) WithContext(ctx context.Context) *userMerchantSubscriptionModelDo {
	return u.userMerchantSubscriptionModelDo.WithContext(ctx)
}

func (u userMerchantSubscriptionModel) TableName() string {
	return u.userMerchantSubscriptionModelDo.TableName()
}

func (u userMerchantSubscriptionModel) Alias() string {
	return u.userMerchantSubscriptionModelDo.Alias()
}

func (u userMerchantSubscriptionModel) Columns(cols ...field.Expr) gen.Columns {
	return u.userMerchantSubscriptionModelDo.Columns(cols...)
}

func (u *userMerchantSubscriptionModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userMerchantSubscriptionModel) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["merchant_id"] = u.MerchantID
	u.fieldMap["is_active"] = u.IsActive
	u.fieldMap["notification_radius"] = u.NotificationRadius
	u.fieldMap["subscribed_at"] = u.SubscribedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u userMerchantSubscriptionModel) clone(db *gorm.DB) userMerchantSubscriptionModel {
	u.userMerchantSubscriptionModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userMerchantSubscriptionModel) replaceDB(db *gorm.DB) userMerchantSubscriptionModel {
	u.userMerchantSubscriptionModelDo.ReplaceDB(db)
	return u
}

type userMerchantSubscriptionModelDo struct{ gen.DO }

func (u userMerchantSubscriptionModelDo) Debug() *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Debug())
}

func (u userMerchantSubscriptionModelDo) WithContext(ctx context.Context) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userMerchantSubscriptionModelDo) ReadDB() *userMerchantSubscriptionModelDo {
	return u.Clauses(dbresolver.Read)
}

func (u userMerchantSubscriptionModelDo) WriteDB() *userMerchantSubscriptionModelDo {
	return u.Clauses(dbresolver.Write)
}

func (u userMerchantSubscriptionModelDo) Session(config *gorm.Session) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Session(config))
}

func (u userMerchantSubscriptionModelDo) Clauses(conds ...clause.Expression) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userMerchantSubscriptionModelDo) Returning(value interface{}, columns ...string) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userMerchantSubscriptionModelDo) Not(conds ...gen.Condition) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userMerchantSubscriptionModelDo) Or(conds ...gen.Condition) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userMerchantSubscriptionModelDo) Select(conds ...field.Expr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userMerchantSubscriptionModelDo) Where(conds ...gen.Condition) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userMerchantSubscriptionModelDo) Order(conds ...field.Expr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userMerchantSubscriptionModelDo) Distinct(cols ...field.Expr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userMerchantSubscriptionModelDo) Omit(cols ...field.Expr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userMerchantSubscriptionModelDo) Join(table schema.Tabler, on ...field.Expr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userMerchantSubscriptionModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userMerchantSubscriptionModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userMerchantSubscriptionModelDo) Group(cols ...field.Expr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userMerchantSubscriptionModelDo) Having(conds ...gen.Condition) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userMerchantSubscriptionModelDo) Limit(limit int) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userMerchantSubscriptionModelDo) Offset(offset int) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userMerchantSubscriptionModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userMerchantSubscriptionModelDo) Unscoped() *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userMerchantSubscriptionModelDo) Create(values ...*model.UserMerchantSubscriptionModel) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userMerchantSubscriptionModelDo) CreateInBatches(values []*model.UserMerchantSubscriptionModel, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userMerchantSubscriptionModelDo) Save(values ...*model.UserMerchantSubscriptionModel) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userMerchantSubscriptionModelDo) First() (*model.UserMerchantSubscriptionModel, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserMerchantSubscriptionModel), nil
	}
}

func (u userMerchantSubscriptionModelDo) Take() (*model.UserMerchantSubscriptionModel, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserMerchantSubscriptionModel), nil
	}
}

func (u userMerchantSubscriptionModelDo) Last() (*model.UserMerchantSubscriptionModel, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserMerchantSubscriptionModel), nil
	}
}

func (u userMerchantSubscriptionModelDo) Find() ([]*model.UserMerchantSubscriptionModel, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserMerchantSubscriptionModel), err
}

func (u userMerchantSubscriptionModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserMerchantSubscriptionModel, err error) {
	buf := make([]*model.UserMerchantSubscriptionModel, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userMerchantSubscriptionModelDo) FindInBatches(result *[]*model.UserMerchantSubscriptionModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userMerchantSubscriptionModelDo) Attrs(attrs ...field.AssignExpr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userMerchantSubscriptionModelDo) Assign(attrs ...field.AssignExpr) *userMerchantSubscriptionModelDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userMerchantSubscriptionModelDo) Joins(fields ...field.RelationField) *userMerchantSubscriptionModelDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userMerchantSubscriptionModelDo) Preload(fields ...field.RelationField) *userMerchantSubscriptionModelDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userMerchantSubscriptionModelDo) FirstOrInit() (*model.UserMerchantSubscriptionModel, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserMerchantSubscriptionModel), nil
	}
}

func (u userMerchantSubscriptionModelDo) FirstOrCreate() (*model.UserMerchantSubscriptionModel, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserMerchantSubscriptionModel), nil
	}
}

func (u userMerchantSubscriptionModelDo) FindByPage(offset int, limit int) (result []*model.UserMerchantSubscriptionModel, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userMerchantSubscriptionModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userMerchantSubscriptionModelDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userMerchantSubscriptionModelDo) Delete(models ...*model.UserMerchantSubscriptionModel) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userMerchantSubscriptionModelDo) withDO(do gen.Dao) *userMerchantSubscriptionModelDo {
	u.DO = *do.(*gen.DO)
	return u
}
