apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../shared/radar

patches:
  - target:
      kind: Service
      name: radar
    patch: |-
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: radar
        annotations:
          run.googleapis.com/ingress: internal
          run.googleapis.com/invoker-iam-disabled: "false"
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/maxScale: "1"
          spec:
            containerConcurrency: 1
            containers:
              - name: app
                resources:
                  limits:
                    memory: 128Mi
