apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../shared/radar

patches:
  - target:
      kind: Service
      name: radar
    patch: |-
      - op: replace
        path: /metadata/annotations/run.googleapis.com~1ingress
        value: internal
      - op: add
        path: /metadata/annotations/run.googleapis.com~1invoker-iam-disabled
        value: "false"
  - target:
      kind: Service
      name: radar
    patch: |-
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: radar
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/maxScale: "1"
              run.googleapis.com/execution-environment: gen1
          spec:
            containerConcurrency: 1
            timeoutSeconds: 1
            containers:
              - name: app
                resources:
                  limits:
                    memory: 128Mi
                    cpu: "1"
