apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../shared/geoworker

patches:
  - target:
      kind: Service
      name: geoworker
    patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1maxScale
        value: "1"
      - op: replace
        path: /spec/template/spec/containerConcurrency
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
